# Generated by Django 2.2.25 on 2022-03-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zgw_consumers", "0012_auto_20210104_1039"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doelgroep",
                    models.CharField(
                        choices=[
                            ("eu-burger", "EU Burger"),
                            ("eu-bedrijf", "EU Bedrijf"),
                        ],
                        help_text="De doelgroep waarvoor deze service is geconfigureerd. ",
                        max_length=32,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zgw_consumers.Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviceconfiguratie",
                "verbose_name_plural": "Serviceconfiguraties",
            },
        ),
        migrations.AddConstraint(
            model_name="serviceconfiguration",
            constraint=models.UniqueConstraint(
                fields=("service", "doelgroep"), name="unique_service_configuration"
            ),
        ),
    ]
