# Generated by Django 2.2.24 on 2021-08-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210827_1824"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                fields=("user", "lokale_overheid"),
                name="unique_user_per_lokaleoverheid",
            ),
        ),
    ]
