# Generated by Django 2.2.24 on 2021-10-12 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20210927_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="lokale_overheid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                to="organisaties.LokaleOverheid",
            ),
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default=django.utils.crypto.get_random_string,
                        max_length=64,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(default=False, verbose_name="accepted"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created"
                    ),
                ),
                ("sent", models.DateTimeField(null=True, verbose_name="sent")),
                (
                    "inviter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitaties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invitaties",
                    ),
                ),
            ],
            options={
                "verbose_name": "user invitation",
                "verbose_name_plural": "user invitations",
            },
        ),
    ]
