# Generated by Django 2.2.24 on 2021-08-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_auto_20210830_1806"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_redacteur",
        ),
        migrations.AddField(
            model_name="user",
            name="is_hoofdredacteur",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user is a root editor (i.e. can edit the reference texts).",
                verbose_name="hoofdredacteur",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_redacteur",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this is an editor of a specific overheidsorganisatie. ",
                verbose_name="redacteur",
            ),
        ),
    ]
