# Generated by Django 2.2.24 on 2021-10-13 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitatie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
