# Generated by Django 2.2.24 on 2021-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_auto_20211018_1443"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=255, verbose_name="voornaam"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, verbose_name="achternaam"),
        ),
    ]
