# Generated by Django 2.2.24 on 2022-01-22 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_auto_20211021_1646"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "rol", "verbose_name_plural": "rollen"},
        ),
        migrations.AlterModelOptions(
            name="userinvitation",
            options={
                "verbose_name": "uitnodiging",
                "verbose_name_plural": "uitnodigingen",
            },
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="geaccepteerd"),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="aangemaakt"
            ),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="sent",
            field=models.DateTimeField(null=True, verbose_name="verzonden"),
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitatie",
                to=settings.AUTH_USER_MODEL,
                verbose_name="gebruiker",
            ),
        ),
    ]
