# Generated by Django 2.2.25 on 2022-05-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_auto_20220122_1516"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["user", "lokale_overheid"],
                "verbose_name": "rol",
                "verbose_name_plural": "rollen",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["first_name", "last_name", "email"],
                "verbose_name": "gebruiker",
                "verbose_name_plural": "gebruikers",
            },
        ),
    ]
