# Generated by Django 3.2.13 on 2022-10-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_options"),
        ("accounts", "0011_role_is_raadpleger"),
    ]

    operations = []
