# Generated by Django 3.2.16 on 2023-04-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_role_is_raadpleger"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="ontvangt_mail",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user receives emails on product changes for this organisation.",
                verbose_name="ontvangt e-mails",
            ),
        ),
    ]
