# Generated by Django 4.2.11 on 2024-03-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_update_ontvangt_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="key",
            field=models.CharField(
                default="FznUE1li2Ldr5fvZC2QSyt9q5N7vs7nxOeAFN8ppUdDuG3mcgWOVKLMrGHT13TXR",
                max_length=64,
                unique=True,
                verbose_name="key",
            ),
        ),
    ]
