# Generated by Django 3.2.23 on 2025-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_update_ontvangt_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="ontvangt_mail",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user receives emails on product changes for this organisation.",
                verbose_name="ontvangt e-mails",
            ),
        ),
    ]
