# Generated by Django 5.2 on 2025-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_role_ontvangt_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="key",
            field=models.CharField(
                default="s6e27lC1s0zedlNY14HmpZHfWU9rlAxK",
                max_length=64,
                unique=True,
                verbose_name="key",
            ),
        ),
    ]
