# Generated by Django 5.2 on 2025-07-16 10:11

import sdg.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_role_ontvangt_mail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="key",
            field=models.CharField(
                default=sdg.accounts.models.get_random_32_char_string,
                max_length=64,
                unique=True,
                verbose_name="key",
            ),
        ),
    ]
