# Generated by Django 2.2.24 on 2021-09-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedproduct",
            name="product",
            field=models.ForeignKey(
                help_text="Het specifieke product van deze vertaling.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertalingen",
                to="producten.Product",
                verbose_name="specifieke product",
            ),
        ),
        migrations.AlterField(
            model_name="localizedproductuitvoering",
            name="productuitvoering",
            field=models.ForeignKey(
                help_text="De productuitvoering van deze vertaling.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertalingen",
                to="producten.Productuitvoering",
                verbose_name="productuitvoering",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="referentie_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Een referentie naar een product. Het toewijzen van een referentieproduct veronderstelt automatisch dat dit product specifiek is.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specifieke_producten",
                to="producten.Product",
                verbose_name="referentie product",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizedgeneriekproduct",
            constraint=models.UniqueConstraint(
                fields=("generiek_product", "taal"),
                name="unique_language_per_generiekproduct",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizedproductuitvoering",
            constraint=models.UniqueConstraint(
                fields=("productuitvoering", "taal"),
                name="unique_language_per_productuitvoering",
            ),
        ),
    ]
