# Generated by Django 2.2.24 on 2021-10-04 16:12
# Data migration

from django.db import migrations


def create_first_version_for_products(apps, schema_editor):
    Product = apps.get_model("producten", "Product")
    ProductVersie = apps.get_model("producten", "ProductVersie")
    User = apps.get_model("accounts", "User")

    try:
        first_user = User.objects.order_by("-is_staff", "-is_superuser", "pk").first()
    except User.DoesNotExist:
        first_user = User.objects.create(
            username="maykin",
            is_active=True,
            email="admin@maykinmedia.nl",
            first_name="Maykin",
            last_name="Media",
        )
        first_user.set_unusable_password()
        first_user.save()

    for product in Product.objects.all():
        product_version = ProductVersie.objects.create(
            product=product, gemaakt_door=first_user, versie=1
        )
        product.vertalingen.all().update(
            product_versie=product_version,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0003_auto_20210928_1636"),
    ]

    operations = [
        migrations.RunPython(create_first_version_for_products),
    ]
