# Generated by Django 2.2.24 on 2021-10-04 16:21
# Post data migration

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0004_auto_20211004_1612"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localizedproduct",
            name="product",
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="product_versie",
            field=models.ForeignKey(
                help_text="Het specifieke product van deze vertaling.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertalingen",
                to="producten.ProductVersie",
                verbose_name="product versie",
                null=False,
            ),
        )
    ]
