# Generated by Django 2.2.24 on 2021-09-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0004_auto_20210928_1801"),
    ]

    operations = [
        migrations.RenameField(
            model_name="localizedproduct",
            old_name="product",
            new_name="product_versie",
        ),
        migrations.AlterField(
            model_name="productversie",
            name="product",
            field=models.ForeignKey(
                help_text="Het product voor het product versie.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versies",
                to="producten.Product",
                verbose_name="product",
            ),
        ),
    ]
