# Generated by Django 2.2.24 on 2021-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0005_auto_20210929_1143"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="localizedproduct",
            name="unique_language_per_product",
        ),
        migrations.AddConstraint(
            model_name="localizedproduct",
            constraint=models.UniqueConstraint(
                fields=("product_versie", "taal"), name="unique_language_per_product"
            ),
        ),
    ]
