# Generated by Django 2.2.24 on 2021-10-05 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0005_auto_20211004_1621"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productversie",
            options={
                "ordering": ("-versie",),
                "verbose_name": "product versie",
                "verbose_name_plural": "product versies",
            },
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="product_versie",
            field=models.ForeignKey(
                help_text="Het specifieke product van deze vertaling.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vertalingen",
                to="producten.ProductVersie",
                verbose_name="specifieke product",
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="gemaakt_door",
            field=models.ForeignKey(
                help_text="De maker van deze productversie.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productversies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="gemaakt door",
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="product",
            field=models.ForeignKey(
                help_text="Het product voor het product versie.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versies",
                to="producten.Product",
                verbose_name="product",
            ),
        ),
        migrations.AddConstraint(
            model_name="localizedproduct",
            constraint=models.UniqueConstraint(
                fields=("product_versie", "taal"),
                name="unique_language_per_productversie",
            ),
        ),
    ]
