# Generated by Django 2.2.24 on 2021-10-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0006_auto_20211005_1617"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="localizedgeneriekproduct",
            options={
                "ordering": ["-taal"],
                "verbose_name": "Vertaald generiek product",
                "verbose_name_plural": "Vertaalde generieke producten",
            },
        ),
        migrations.AlterModelOptions(
            name="localizedproduct",
            options={
                "ordering": ["-taal"],
                "verbose_name": "vertaald product",
                "verbose_name_plural": "vertaalde producten",
            },
        ),
        migrations.AlterModelOptions(
            name="localizedproductuitvoering",
            options={
                "ordering": ["-taal"],
                "verbose_name": "vertaalde productuitvoering",
                "verbose_name_plural": "vertaalde productuitvoeringen",
            },
        ),
    ]
