# Generated by Django 2.2.24 on 2021-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0006_auto_20210929_1154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productversie",
            name="publicatie_datum",
            field=models.DateTimeField(
                blank=True,
                help_text="De datum van publicatie van de productversie.",
                null=True,
                verbose_name="publicatie datum",
            ),
        ),
    ]
