# Generated by Django 2.2.24 on 2021-10-19 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0007_auto_20211005_1840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productversie",
            name="publicatie_datum",
            field=models.DateField(
                blank=True,
                help_text="De datum van publicatie van de productversie.",
                null=True,
                verbose_name="publicatie datum",
            ),
        ),
    ]
