# Generated by Django 2.2.24 on 2021-10-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0007_auto_20211005_1840"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="localizedproduct",
            name="unique_language_per_product",
        ),
    ]
