# Generated by Django 2.2.24 on 2021-10-26 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0008_auto_20211019_1946"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="korte_omschrijving",
            field=models.CharField(
                help_text='Korte omschrijving van wat er op de pagina staat, gebruikt in de meta tags van de productpagina (meta name="description"). Deze tekst wordt gebruikt om te tonen wanneer de pagina wordt gevonden in een zoekmachine. ',
                max_length=160,
                verbose_name="korte omschrijving",
            ),
        ),
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="verwijzing_links",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.URLField(
                    max_length=1000, verbose_name="url van verwijzing"
                ),
                blank=True,
                default=list,
                help_text="Zowel de Nationale Portalen als de decentrale overheden kunnen een x-tal 'verwijzingen' opnemen bij een product. Voorstel hierbij om zo'n 'verwijzing' te laten bestaan uit een -bij elkaar horende-  beschrijving en hyperlink. De tekst van artikel 9 geeft enkele voorbeelden hiervan: 'richtsnoeren/ NEN-specs bijv en ook links naar de wetgeving (dit laatste is inderdaad te verstaan als vertaling van 'Legal Acts'. Bart heeft dit bij Jurist van bNC (Vanessa) gecheckt. ",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="verwijzing_links",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.URLField(
                    max_length=1000, verbose_name="url van verwijzing"
                ),
                blank=True,
                default=list,
                help_text="Decentrale verwijzingen.",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="gemaakt_door",
            field=models.ForeignKey(
                blank=True,
                help_text="De maker van deze productversie.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productversies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="gemaakt door",
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Het product voor het product versie.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versies",
                to="producten.Product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="versie",
            field=models.PositiveIntegerField(
                blank=True,
                default=1,
                help_text="Het versienummer van het product.",
                verbose_name="versie",
            ),
        ),
    ]
