# Generated by Django 2.2.24 on 2021-11-15 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0009_auto_20211026_1227"),
        ("producten", "0009_auto_20211029_1238"),
    ]

    operations = []
