# Generated by Django 2.2.24 on 2021-11-15 16:36

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0009_auto_20211026_1227"),
    ]

    operations = [
        migrations.AddField(
            model_name="localizedgeneriekproduct",
            name="verwijzing_links_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                help_text="Zowel de Nationale Portalen als de decentrale overheden kunnen een x-tal 'verwijzingen' opnemen bij een product. Voorstel hierbij om zo'n 'verwijzing' te laten bestaan uit een -bij elkaar horende-  beschrijving en hyperlink. De tekst van artikel 9 geeft enkele voorbeelden hiervan: 'richtsnoeren/ NEN-specs bijv en ook links naar de wetgeving (dit laatste is inderdaad te verstaan als vertaling van 'Legal Acts'. Bart heeft dit bij Jurist van bNC (Vanessa) gecheckt. ",
                size=None,
                validators=[sdg.core.models.validators.validate_labeled_url],
            ),
        ),
        migrations.AddField(
            model_name="localizedproduct",
            name="verwijzing_links_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                help_text="Decentrale verwijzingen.",
                size=None,
                validators=[sdg.core.models.validators.validate_labeled_url],
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="verwijzing_links",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.URLField(
                    max_length=1000, verbose_name="url van verwijzing"
                ),
                help_text="Decentrale verwijzingen.",
                size=None,
            ),
        ),
    ]
