# Generated by Django 2.2.24 on 2021-11-15 16:39

from django.db import migrations


def create_first_version_for_products(apps, schema_editor):
    LocalizedGeneriekProduct = apps.get_model("producten", "LocalizedGeneriekProduct")
    LocalizedProduct = apps.get_model("producten", "LocalizedProduct")

    for lp in LocalizedProduct.objects.all():
        lp.verwijzing_links_tmp = [
            [f"Link #{idx}", url] for idx, url in enumerate(lp.verwijzing_links)
        ]
        lp.save()

    for lgp in LocalizedGeneriekProduct.objects.all():
        lgp.verwijzing_links_tmp = [
            [f"Link #{idx}", url] for idx, url in enumerate(lgp.verwijzing_links)
        ]
        lgp.save()


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0010_auto_20211115_1636"),
    ]

    operations = [
        migrations.RunPython(
            create_first_version_for_products, migrations.RunPython.noop
        ),
    ]
