# Generated by Django 2.2.24 on 2021-11-08 15:54

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    Product = apps.get_model("producten", "Product")
    for obj in Product.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0010_auto_20211108_1407"),
    ]

    operations = [
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="product",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
