# Generated by Django 2.2.24 on 2021-11-15 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0010_merge_20211115_1249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generiekproduct",
            name="upn",
            field=models.ForeignKey(
                help_text="De uniforme productnaam met betrekking tot dit product.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generieke_producten",
                to="core.UniformeProductnaam",
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="gemaakt_door",
            field=models.ForeignKey(
                blank=True,
                help_text="De maker van deze productversie.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productversies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="gemaakt door",
            ),
        ),
    ]
