# Generated by Django 2.2.24 on 2021-11-15 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0011_data_migration_labeled_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localizedproduct",
            name="verwijzing_links",
        ),
        migrations.RemoveField(
            model_name="localizedgeneriekproduct",
            name="verwijzing_links",
        ),
        migrations.RenameField(
            model_name="localizedproduct",
            old_name="verwijzing_links_tmp",
            new_name="verwijzing_links",
        ),
        migrations.RenameField(
            model_name="localizedgeneriekproduct",
            old_name="verwijzing_links_tmp",
            new_name="verwijzing_links",
        ),
    ]
