# Generated by Django 2.2.24 on 2021-11-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0011_auto_20211115_1301"),
        ("producten", "0012_post_data_migration_labeled_url"),
    ]

    operations = []
