# Generated by Django 2.2.24 on 2021-11-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0013_merge_20211116_1647"),
        ("producten", "0012_merge_20211116_1604"),
    ]

    operations = []
