# Generated by Django 2.2.24 on 2021-11-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0014_data_migration_beschikbaar_aanwezig"),
        ("producten", "0014_merge_20211117_1620"),
    ]

    operations = []
