# Generated by Django 2.2.24 on 2022-01-03 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0016_auto_20211123_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="localizedproduct",
            name="datum_check",
            field=models.DateTimeField(
                blank=True,
                help_text="Datum waarop de informatie voor deze versie van het product is gecontroleerd. ",
                null=True,
                verbose_name="datum check",
            ),
        ),
    ]
