# Generated by Django 2.2.24 on 2022-01-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0017_auto_20211220_1223"),
        ("producten", "0017_auto_20220103_1609"),
    ]

    operations = []
