# Generated by Django 2.2.24 on 2022-01-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0019_auto_20220122_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generiekproduct",
            name="doelgroep",
            field=models.CharField(
                choices=[("eu-burger", "EU Burger"), ("eu-bedrijf", "EU Bedrijf")],
                help_text="Geeft aan voor welke doelgroep het product is bedoeld: burgers, bedrijven of burgers en bedrijven. Wordt gebruikt wanneer een portaal informatie over het product ophaalt uit de invoervoorziening. Zo krijgen de ondernemersportalen de ondernemersvariant en de burgerportalen de burgervariant. ",
                max_length=32,
            ),
        )
    ]
