# Generated by Django 2.2.25 on 2022-03-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0020_auto_20220126_1722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="product_titel",
            field=models.CharField(
                help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                max_length=80,
                verbose_name="product titel",
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="product_titel_decentraal",
            field=models.CharField(
                blank=True,
                help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                max_length=80,
                verbose_name="product titel decentraal",
            ),
        ),
        migrations.AlterField(
            model_name="localizedproductuitvoering",
            name="product_titel_uitvoering",
            field=models.CharField(
                help_text="De titel van de uitvoering van het product.",
                max_length=80,
                verbose_name="product titel uitvoering",
            ),
        ),
    ]
