# Generated by Django 2.2.24 on 2022-03-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0020_auto_20220126_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="localizedproduct",
            name="product_valt_onder_toelichting",
            field=models.TextField(
                blank=True,
                help_text="Toelichting over het product valt onder.",
                verbose_name="product valt onder toelichting",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_valt_onder",
            field=models.ForeignKey(
                blank=True,
                help_text="Een verwijzing naar een product waarvan dit product valt onder.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="producten.Product",
                verbose_name="product valt onder",
            ),
        ),
    ]
