# Generated by Django 2.2.25 on 2022-03-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0021_auto_20220304_1634"),
        ("producten", "0021_auto_20220317_1151"),
    ]

    operations = []
