# Generated by Django 2.2.25 on 2022-03-24 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0017_auto_20220324_1221"),
        ("producten", "0022_merge_20220317_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bevoegde_organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="De bevoegde organisatie van de producten.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="producten",
                to="organisaties.BevoegdeOrganisatie",
                verbose_name="bevoegde organisatie",
            ),
        ),
    ]
