# Generated by Django 2.2.25 on 2022-04-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0023_product_bevoegde_organisatie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_aanwezig_toelichting",
        ),
        migrations.AddField(
            model_name="localizedproduct",
            name="product_aanwezig_toelichting",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Toelichting",
                verbose_name="aanwezig toelichting",
            ),
        ),
    ]
