# Generated by Django 2.2.25 on 2022-04-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0024_auto_20220404_1509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="product_titel",
            field=models.CharField(
                help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                max_length=100,
                verbose_name="product titel",
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="product_titel_decentraal",
            field=models.CharField(
                blank=True,
                help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                max_length=100,
                verbose_name="product titel decentraal",
            ),
        ),
    ]
