# Generated by Django 2.2.25 on 2022-04-25 18:24

from django.db import migrations


def remove_zombie_products(apps, schema_editor):
    Product = apps.get_model("producten", "Product")
    Product.objects.filter(generiek_product=None, referentie_product=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0025_auto_20220408_1439"),
    ]

    operations = [
        migrations.RunPython(remove_zombie_products, migrations.RunPython.noop),
    ]
