# Generated by Django 2.2.25 on 2022-04-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0025_auto_20220408_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="referentie_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Een referentie naar een product. Het toewijzen van een referentieproduct veronderstelt automatisch dat dit product specifiek is.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifieke_producten",
                to="producten.Product",
                verbose_name="referentie product",
            ),
        ),
    ]
