# Generated by Django 2.2.25 on 2022-04-25 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0028_auto_20220425_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="bevoegde_organisatie",
            field=models.ForeignKey(
                help_text="De bevoegde organisatie van de producten.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producten",
                to="organisaties.BevoegdeOrganisatie",
                verbose_name="bevoegde organisatie",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="referentie_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Een referentie naar een product. Het toewijzen van een referentieproduct veronderstelt automatisch dat dit product specifiek is.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="specifieke_producten",
                to="producten.Product",
                verbose_name="referentie product",
            ),
        ),
    ]
