# Generated by Django 3.2.13 on 2022-05-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0029_auto_20220425_1911"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generiekproduct",
            options={
                "ordering": ["doelgroep"],
                "verbose_name": "generiek product",
                "verbose_name_plural": "generieke producten",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": [
                    "generiek_product__upn__upn_label",
                    "referentie_product__generiek_product__upn__upn_label",
                ],
                "verbose_name": "product",
                "verbose_name_plural": "producten",
            },
        ),
    ]
