# Generated by Django 3.2.13 on 2022-05-06 18:13

from django.db import migrations
from django.db.models import Subquery, OuterRef


def set_generic_product_for_all(apps, schema_editor):
    Product = apps.get_model("producten", "Product")
    Product.objects.filter(referentie_product__isnull=False).update(
        generiek_product=Subquery(
            Product.objects.filter(pk=OuterRef("pk")).values(
                "referentie_product__generiek_product"
            )[:1]
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0029_auto_20220425_1911"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="generic_or_reference",
        ),
        migrations.RunPython(set_generic_product_for_all, migrations.RunPython.noop),
    ]
