# Generated by Django 2.2.25 on 2022-05-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0029_auto_20220425_1911"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="generiekproduct",
            options={
                "ordering": ["upn", "verantwoordelijke_organisatie"],
                "verbose_name": "generiek product",
                "verbose_name_plural": "generieke producten",
            },
        ),
        migrations.AlterModelOptions(
            name="localizedgeneriekproduct",
            options={
                "ordering": ["-taal", "product_titel"],
                "verbose_name": "Vertaald generiek product",
                "verbose_name_plural": "Vertaalde generieke producten",
            },
        ),
        migrations.AlterModelOptions(
            name="localizedproduct",
            options={
                "ordering": ["-taal", "product_titel_decentraal"],
                "verbose_name": "vertaald product",
                "verbose_name_plural": "vertaalde producten",
            },
        ),
        migrations.AlterModelOptions(
            name="localizedproductuitvoering",
            options={
                "ordering": ["-taal", "product_titel_uitvoering"],
                "verbose_name": "vertaalde productuitvoering",
                "verbose_name_plural": "vertaalde productuitvoeringen",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["generiek_product", "referentie_product", "catalogus"],
                "verbose_name": "product",
                "verbose_name_plural": "producten",
            },
        ),
        migrations.AlterModelOptions(
            name="productuitvoering",
            options={
                "ordering": ["product"],
                "verbose_name": "productuitvoering",
                "verbose_name_plural": "productuitvoeringen",
            },
        ),
        migrations.AlterModelOptions(
            name="productversie",
            options={
                "ordering": ("-versie", "product"),
                "verbose_name": "product versie",
                "verbose_name_plural": "product versies",
            },
        ),
    ]
