# Generated by Django 3.2.13 on 2022-05-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0030_auto_20220506_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="generiek_product",
            field=models.ForeignKey(
                help_text="Het generiek product gekoppeld aan dit product.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="producten",
                to="producten.generiekproduct",
                verbose_name="generiek product",
            ),
        ),
    ]
