# Generated by Django 3.2.13 on 2022-08-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0032_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="generiekproduct",
            name="eind_datum",
            field=models.DateField(
                blank=True,
                help_text="De datum wanneer het product komt te vervallen.",
                null=True,
                verbose_name="Eind datum",
            ),
        ),
    ]
