# Generated by Django 3.2.13 on 2022-08-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0033_alter_localizedgeneriekproduct_landelijke_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gerelateerde_producten",
        ),
    ]
