# Generated by Django 3.2.13 on 2022-08-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0033_alter_localizedgeneriekproduct_landelijke_link"),
        ("producten", "0033_generiekproduct_eind_datum"),
    ]

    operations = []
