# Generated by Django 3.2.13 on 2022-09-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0034_merge_20220810_1258"),
        ("producten", "0034_remove_product_gerelateerde_producten"),
    ]

    operations = []
