# Generated by Django 3.2.13 on 2022-09-22 12:47

from django.db import migrations
import sdg.producten.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0035_merge_20220906_1028"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="generieke_tekst",
            field=sdg.producten.models.fields.MarkdownxField(
                help_text="De Nationale Portalen schrijven een inleidende, algemene tekst over het product. Dit veld ondersteund Markdown.",
                verbose_name="generieke tekst",
            ),
        ),
    ]
