# Generated by Django 3.2.13 on 2022-09-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0036_alter_localizedgeneriekproduct_generieke_tekst"),
    ]

    operations = [
        migrations.AddField(
            model_name="localizedproduct",
            name="decentrale_procedure_link_label",
            field=models.CharField(
                blank=True,
                help_text="Label van de 'decentrale procedure link url'",
                max_length=50,
                verbose_name="decentrale procedure link label",
            ),
        ),
    ]
