# Generated by Django 3.2.13 on 2022-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0037_localizedproduct_decentrale_procedure_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="heeft_kosten",
            field=models.BooleanField(
                default=False,
                help_text="Heeft dit product kosten?",
                verbose_name="heeft kosten",
            ),
        ),
    ]
