# Generated by Django 3.2.13 on 2022-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0037_localizedproduct_decentrale_procedure_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="generiekproduct",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("new", "Nieuw"),
                    ("ready_admin", "Gereed voor beheer"),
                    ("ready_publication", "Gereed voor publicatie"),
                    ("expired_in_upl", "Vervallen in de UPL"),
                    ("eol", "Wordt binnenkort verwijderd"),
                    ("deleted", "Verwijderd"),
                    ("missing", "Geen referentie producten gevonden"),
                ],
                default="new",
                max_length=32,
            ),
        ),
    ]
