# Generated by Django 3.2.13 on 2022-10-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0038_auto_20221003_1433"),
    ]

    operations = [
        migrations.AddField(
            model_name="generiekproduct",
            name="product_status",
            field=models.CharField(
                choices=[
                    ("new", "Nieuw"),
                    ("ready_admin", "Gereed voor beheer"),
                    ("ready_publication", "Gereed voor publicatie"),
                    ("expired_in_upl", "Vervallen in de UPL"),
                    ("eol", "Wordt binnenkort verwijderd"),
                    ("deleted", "Verwijderd"),
                    ("missing", "Geen referentie producten gevonden"),
                ],
                default="new",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="heeft_kosten",
            field=models.BooleanField(
                default=False,
                help_text="Heeft dit product kosten?",
                verbose_name="heeft kosten",
            ),
        ),
    ]
