# Generated by Django 3.2.13 on 2022-10-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0038_auto_20221003_1433"),
        ("producten", "0038_generiekproduct_product_status"),
    ]

    operations = []
