# Generated by Django 3.2.13 on 2022-10-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0038_auto_20221003_1433"),
        ("producten", "0039_product_has_costs__data_migration"),
    ]

    operations = []
