# Generated by Django 3.2.16 on 2022-12-16 16:01

import django.contrib.postgres.fields
from django.db import migrations, models
import functools
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_productencatalogus_options"),
        ("producten", "0043_product_api_verborgen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="verwijzing_links",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                help_text="Zowel de Nationale Portalen als de decentrale overheden kunnen een x-tal 'verwijzingen' opnemen bij een product. Voorstel hierbij om zo'n 'verwijzing' te laten bestaan uit een -bij elkaar horende-  beschrijving en hyperlink. De tekst van artikel 9 geeft enkele voorbeelden hiervan: 'richtsnoeren/ NEN-specs bijv en ook links naar de wetgeving (dit laatste is inderdaad te verstaan als vertaling van 'Legal Acts'. Bart heeft dit bij Jurist van bNC (Vanessa) gecheckt. ",
                size=None,
                validators=[
                    functools.partial(
                        sdg.core.models.validators.validate_labeled_url,
                        *(),
                        **{"length": 3}
                    )
                ],
            ),
        ),
    ]
