# Generated by Django 3.2.16 on 2022-12-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_productencatalogus_options"),
        ("producten", "0045_localized_generic__data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generiekproduct",
            name="verantwoordelijke_organisatie",
        ),
        migrations.AddField(
            model_name="localizedgeneriekproduct",
            name="laatst_gewijzigd",
            field=models.DateTimeField(
                blank=True,
                help_text="Laatst gewijzigd datum. Datum heeft het formaat [datum]T[tijd]",
                null=True,
                verbose_name="laatst gewijzigd",
            ),
        ),
        migrations.AddField(
            model_name="localizedgeneriekproduct",
            name="uuid",
            field=models.UUIDField(
                editable=False,
                help_text="De identificatie die binnen deze API gebruikt wordt voor de resource.",
                null=True,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.CreateModel(
            name="GeneriekProductOverheidsorganisatieRol",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(blank=True, max_length=100, verbose_name="rol"),
                ),
                (
                    "generiek_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="producten.generiekproduct",
                    ),
                ),
                (
                    "overheidsorganisatie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.overheidsorganisatie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="generiekproduct",
            name="verantwoordelijke_organisaties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Organisaties verantwoordelijk voor de landelijke informatie",
                through="producten.GeneriekProductOverheidsorganisatieRol",
                to="core.Overheidsorganisatie",
                verbose_name="verantwoordelijke organisaties",
            ),
        ),
    ]
