# Generated by Django 3.2.16 on 2023-01-02 16:37

from django.db import migrations, models
import sdg.producten.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0046_auto_20221219_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="generieke_tekst",
            field=sdg.producten.models.fields.MarkdownxField(
                blank=True,
                help_text="De Nationale Portalen schrijven een inleidende, algemene tekst over het product. Dit veld ondersteunt Markdown.",
                verbose_name="generieke tekst",
            ),
        ),
        migrations.AlterField(
            model_name="productversie",
            name="bewerkte_velden",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="bewerkte_velden"
            ),
        ),
    ]
