# Generated by Django 3.2.16 on 2023-01-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0047_auto_20230102_1637"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="product_titel",
            field=models.CharField(
                blank=True,
                help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                max_length=150,
                verbose_name="product titel",
            ),
        ),
    ]
