# Generated by Django 3.2.16 on 2023-01-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0048_alter_localizedgeneriekproduct_product_titel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedproduct",
            name="product_titel_decentraal",
            field=models.CharField(
                blank=True,
                help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                max_length=150,
                verbose_name="product titel decentraal",
            ),
        ),
    ]
