# Generated by Django 3.2.16 on 2023-02-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0050_auto_20230203_1143"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productversie",
            unique_together={("versie", "product")},
        ),
    ]
