# Generated by Django 3.2.16 on 2023-03-31 15:11

from django.db import migrations, models
import sdg.producten.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0051_alter_productversie_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedgeneriekproduct",
            name="landelijke_link",
            field=models.URLField(
                blank=True,
                help_text="URL van de productpagina wanneer het een landelijk product betreft of de pagina met enkel generieke beschrijving van een decentraal product, bijvoorbeeld : https://ondernemersplein.kvk.nl/terrasvergunning. gebruikt voor o.a. notificeren, feedback & statistics en het kunnen bekijken van de generieke productinformatie (bv door gebruikers van de organisatie invoervoorziening) ",
                validators=[sdg.producten.models.validators.validate_https],
                verbose_name="landelijke link",
            ),
        ),
        migrations.AlterField(
            model_name="localizedproduct",
            name="decentrale_procedure_link",
            field=models.URLField(
                blank=True,
                help_text="Link naar de procedure voor burgers en / of bedrijven.",
                validators=[sdg.producten.models.validators.validate_https],
                verbose_name="decentrale procedure link",
            ),
        ),
    ]
