# Generated by Django 3.2.16 on 2023-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0051_alter_productversie_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="localizedgeneriekproduct",
            name="published_url",
            field=models.URLField(
                blank=True,
                help_text="De gepubliceerde website url.",
                verbose_name="Gepubliceerde url link",
            ),
        ),
    ]
