# Generated by Django 3.2.16 on 2023-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0051_alter_productversie_unique_together"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE producten_localizedproduct \
            SET product_valt_onder_toelichting = REPLACE(product_valt_onder_toelichting, ' omdat...', '.') \
            WHERE product_valt_onder_toelichting LIKE '% omdat...%'; \
            UPDATE producten_localizedproduct \
            SET product_valt_onder_toelichting = REPLACE(product_valt_onder_toelichting, ' omdat ...', '.') \
            WHERE product_valt_onder_toelichting LIKE '% omdat ...%';"
        ),
        migrations.RunSQL(
            "UPDATE producten_localizedproduct \
            SET product_aanwezig_toelichting = REPLACE(product_aanwezig_toelichting, ' omdat...', '.') \
            WHERE product_aanwezig_toelichting LIKE '% omdat...%'; \
            UPDATE producten_localizedproduct \
            SET product_aanwezig_toelichting = REPLACE(product_aanwezig_toelichting, ' omdat ...', '.') \
            WHERE product_aanwezig_toelichting LIKE '% omdat ...%';"
        ),
    ]
