# Generated by Django 3.2.16 on 2023-04-06 13:30

from django.db import migrations
from django.db.models import Func, Value, Q


class Replace(Func):
    function = "REPLACE"


def replace_toelichting_field_omdat_value_with_dot(apps, schema_editor):
    LocalizedProduct = apps.get_model("producten", "localizedproduct")

    LocalizedProduct.objects.filter(
        Q(product_valt_onder_toelichting__icontains=" omdat...")
        | Q(product_valt_onder_toelichting__icontains="omdat...")
        | Q(product_aanwezig_toelichting__icontains=" omdat...")
        | Q(product_aanwezig_toelichting__icontains="omdat...")
    ).update(
        product_valt_onder_toelichting=Replace(
            Replace("product_valt_onder_toelichting", Value(" omdat..."), Value(".")),
            Value("omdat..."),
            Value("."),
        ),
        product_aanwezig_toelichting=Replace(
            Replace("product_aanwezig_toelichting", Value(" omdat..."), Value(".")),
            Value("omdat..."),
            Value("."),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0051_alter_productversie_unique_together"),
    ]

    operations = [
        migrations.RunPython(
            replace_toelichting_field_omdat_value_with_dot, migrations.RunPython.noop
        )
    ]
