# Generated by Django 3.2.16 on 2023-03-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0052_auto_20230331_1511"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE producten_localizedproduct \
            SET decentrale_procedure_link = REPLACE(decentrale_procedure_link, 'http', 'https') \
            WHERE decentrale_procedure_link LIKE 'http:%';"
        ),
        migrations.RunSQL(
            "UPDATE producten_localizedgeneriekproduct \
            SET landelijke_link = REPLACE(landelijke_link, 'http', 'https') \
            WHERE landelijke_link LIKE 'http:%';"
        ),
    ]
