# Generated by Django 3.2.16 on 2023-04-14 11:31

from django.db import migrations
from django.utils.text import slugify


def generate_published_urls(apps, schema_editor):
    LocalizedGeneriekProduct = apps.get_model("producten", "LocalizedGeneriekProduct")

    for org in LocalizedGeneriekProduct.objects.filter(slug="", product_titel__gt=""):
        org.slug = slugify(org.product_titel)
        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0052_localizedgeneriekproduct_slug"),
    ]

    operations = [
        migrations.RunPython(generate_published_urls, migrations.RunPython.noop)
    ]
