# Generated by Django 3.2.16 on 2023-04-13 10:55

from compat import slugify
from django.db import migrations

from sdg.core.constants.product import DoelgroepChoices, TaalChoices


def generate_published_urls(apps, schema_editor):
    LocalizedGeneriekProduct = apps.get_model("producten", "LocalizedGeneriekProduct")

    for org in LocalizedGeneriekProduct.objects.filter(
        published_url="", product_titel__gt=""
    ):
        doelgroep = org.generiek_product.doelgroep
        if doelgroep == DoelgroepChoices.bedrijf:
            if org.taal == TaalChoices.nl:
                org.published_url = f"https://ondernemersplein.kvk.nl/{slugify(org.product_titel)}/gemeente/"
            elif org.taal == TaalChoices.en:
                org.published_url = f"https://business.gov.nl/regulation/{slugify(org.product_titel)}/municipality/"

        elif doelgroep == DoelgroepChoices.burger:
            if org.taal == TaalChoices.nl:
                org.published_url = f"https://www.nederlandwereldwijd.nl/regelen-in-nederland/{slugify(org.product_titel)}/gemeente-"
            elif org.taal == TaalChoices.en:
                org.published_url = f"https://www.netherlandsworldwide.nl/government-services-in-the-netherlands/{slugify(org.product_titel)}/gemeente-"

        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0052_localizedgeneriekproduct_published_url"),
    ]

    operations = [
        migrations.RunPython(generate_published_urls, migrations.RunPython.noop)
    ]
