# Generated by Django 3.2.16 on 2023-04-04 11:26

from django.db import migrations


def alter_generic_verwijzing_links(apps, schema_editor):
    localized_products = apps.get_model("producten", "LocalizedGeneriekProduct")
    localized_products = localized_products.objects.exclude(verwijzing_links__exact=[])
    for product in localized_products:
        new_verwijzing_links = []
        update = False
        for labeled_link in product.verwijzing_links:
            if labeled_link[1].startswith("http:"):
                new_labeled_link = [
                    labeled_link[0],
                    labeled_link[1].replace("http", "https"),
                    labeled_link[2],
                ]
                new_verwijzing_links.append(new_labeled_link)
                update = True
            else:
                new_verwijzing_links.append(labeled_link)

        if update:
            product.verwijzing_links = new_verwijzing_links
            product.save()
        else:
            new_verwijzing_links = []
            update = False


def alter_localized_verwijzing_links(apps, schema_editor):
    localized_products = apps.get_model("producten", "LocalizedProduct")
    localized_products = localized_products.objects.exclude(verwijzing_links__exact=[])
    for product in localized_products:
        new_verwijzing_links = []
        update = False
        for labeled_link in product.verwijzing_links:
            if labeled_link[1].startswith("http:"):
                new_labeled_link = [
                    labeled_link[0],
                    labeled_link[1].replace("http", "https"),
                ]
                new_verwijzing_links.append(new_labeled_link)
                update = True
            else:
                new_verwijzing_links.append(labeled_link)

        if update:
            product.verwijzing_links = new_verwijzing_links
            product.save()
        else:
            new_verwijzing_links = []
            update = False


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0053_alter_links"),
    ]

    operations = [
        migrations.RunPython(alter_generic_verwijzing_links, migrations.RunPython.noop),
        migrations.RunPython(
            alter_localized_verwijzing_links, migrations.RunPython.noop
        ),
    ]
