# Generated by Django 3.2.16 on 2023-05-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0052_rename_toelichting_fields"),
        ("producten", "0053_generate_slug"),
        ("producten", "0054_alter_verwijzing_links"),
    ]

    operations = []
