# Generated by Django 3.2.18 on 2023-05-04 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0055_merge_20230502_1438"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localizedgeneriekproduct",
            name="slug",
        ),
    ]
