# Generated by Django 3.2.18 on 2023-08-23 21:42

from django.db import migrations
from django.db.models import Q


def remove_unwanted_toelichting_fields(apps, schema_editor):
    LocalizedProducts = apps.get_model("producten", "LocalizedProduct")
    for LocalizedProduct in LocalizedProducts.objects.filter(
        ~Q(product_aanwezig_toelichting__exact="")
    ):
        if (
            LocalizedProduct.product_versie.product.product_aanwezig
            or LocalizedProduct.product_versie.product.product_aanwezig is None
        ):
            LocalizedProduct.product_aanwezig_toelichting = ""
            LocalizedProduct.save()


class Migration(migrations.Migration):
    dependencies = [
        ("producten", "0056_remove_localizedgeneriekproduct_slug"),
    ]

    operations = [
        migrations.RunPython(
            remove_unwanted_toelichting_fields, migrations.RunPython.noop
        ),
    ]
