# Generated by Django 3.2.18 on 2024-01-30 10:47

from django.db import migrations, models
import sdg.producten.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("producten", "0057_remove_unwanted_toelichting_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedproduct",
            name="decentrale_procedure_link",
            field=models.URLField(
                blank=True,
                help_text="Link naar de procedure voor burgers en / of bedrijven.",
                max_length=1000,
                validators=[sdg.producten.models.validators.validate_https],
                verbose_name="decentrale procedure link",
            ),
        ),
    ]
