# Generated by Django 3.2.23 on 2024-10-21 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("producten", "0058_alter_localizedproduct_decentrale_procedure_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationViewed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_viewed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "gebruiker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
