# Generated by Django 3.2.23 on 2024-11-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0059_brokenlinks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokenlinks",
            name="url",
            field=models.URLField(default="", max_length=2000),
        ),
    ]
