# Generated by Django 3.2.23 on 2024-11-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0059_notificationviewed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationviewed",
            name="last_viewed_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
