# Generated by Django 3.2.23 on 2024-11-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0060_alter_brokenlinks_url'),
        ('producten', '0060_alter_notificationviewed_last_viewed_date'),
    ]

    operations = [
    ]
