# Generated by Django 3.2.23 on 2024-11-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0059_auto_20241126_1513"),
        ("producten", "0060_alter_notificationviewed_last_viewed_date"),
    ]

    operations = []
