# Generated by Django 3.2.23 on 2024-12-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0061_merge_20241126_1232"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productversie",
            options={
                "ordering": ("-gewijzigd_op",),
                "verbose_name": "product versie",
                "verbose_name_plural": "product versies",
            },
        ),
        migrations.RenameField(
            model_name="brokenlinks",
            old_name="occuring_field",
            new_name="occurring_field",
        ),
        migrations.AddField(
            model_name="brokenlinks",
            name="url_label",
            field=models.TextField(default=""),
        ),
    ]
