# Generated by Django 3.2.23 on 2024-12-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producten', '0061_merge_20241126_1717'),
        ('producten', '0062_auto_20241202_1600'),
    ]

    operations = [
    ]
