# Generated by Django 3.2.23 on 2025-02-27 17:28

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("producten", "0063_merge_20241210_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="localizedproduct",
            name="verwijzing_links",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                error_messages={
                    "nested_array_mismatch": "De link moet een label en een URL bevatten."
                },
                help_text="Decentrale verwijzingen.",
                size=None,
                validators=[sdg.core.models.validators.validate_labeled_url],
            ),
        ),
    ]
