# Generated by Django 2.2.24 on 2021-09-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sdg.core.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LokaleOverheid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_naam",
                    models.CharField(
                        help_text="De naam van de verantwoordelijke contactpersoon.",
                        max_length=40,
                        verbose_name="contact naam",
                    ),
                ),
                (
                    "contact_website",
                    models.URLField(
                        blank=True,
                        help_text="De website van de verantwoordelijke contactpersoon.",
                        null=True,
                        verbose_name="contact website",
                    ),
                ),
                (
                    "contact_telefoonnummer",
                    models.CharField(
                        blank=True,
                        help_text="Het telefoonnummer van de verantwoordelijke contactpersoon.",
                        max_length=20,
                        null=True,
                        verbose_name="contact telefoonnummer",
                    ),
                ),
                (
                    "contact_emailadres",
                    models.EmailField(
                        blank=True,
                        help_text="Het e-mailadres van de verantwoordelijke contactpersoon.",
                        max_length=254,
                        null=True,
                        verbose_name="contact emailadres",
                    ),
                ),
                (
                    "lau_code",
                    models.CharField(
                        blank=True,
                        help_text="Een geldige LAU-code van de organisatie.",
                        max_length=5,
                        null=True,
                        validators=[sdg.core.models.validators.validate_lau],
                        verbose_name="LAU-code",
                    ),
                ),
                (
                    "bevoegde_organisatie",
                    models.ForeignKey(
                        help_text="Bevoegd gezag verantwoordelijk voor de procedure.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bevoegde",
                        to="core.Overheidsorganisatie",
                        verbose_name="bevoegde organisatie",
                    ),
                ),
                (
                    "ondersteunings_organisatie",
                    models.ForeignKey(
                        help_text="Organisatie voor ondersteuning.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ondersteunings",
                        to="core.Overheidsorganisatie",
                        verbose_name="ondersteunings organisatie",
                    ),
                ),
                (
                    "organisatie",
                    models.ForeignKey(
                        help_text="De organisatie van de lokale overheid.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organisatie",
                        to="core.Overheidsorganisatie",
                        verbose_name="organisatie",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        through="accounts.Role", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "verantwoordelijke_organisatie",
                    models.ForeignKey(
                        help_text="Organisatie verantwoordelijk voor de decentrale informatie.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verantwoordelijke",
                        to="core.Overheidsorganisatie",
                        verbose_name="verantwoordelijke organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "lokale overheid",
                "verbose_name_plural": "lokale overheden",
            },
        ),
        migrations.CreateModel(
            name="Lokatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van de lokatie.",
                        max_length=40,
                        verbose_name="naam",
                    ),
                ),
                (
                    "lokatie_adres",
                    models.TextField(
                        help_text="De gegevens over het adres van de lokatie.",
                        max_length=1000,
                        verbose_name="lokatie adres",
                    ),
                ),
                (
                    "lokale_overheid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lokaties",
                        to="organisaties.LokaleOverheid",
                        verbose_name="lokale overheid",
                    ),
                ),
            ],
            options={
                "verbose_name": "lokatie",
                "verbose_name_plural": "lokaties",
            },
        ),
    ]
