# Generated by Django 2.2.24 on 2021-08-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokatie",
            name="naam",
            field=models.CharField(
                default="Lokatie naam",
                help_text="De naam van de lokatie.",
                max_length=40,
                verbose_name="naam",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lokatie",
            name="lokale_overheid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lokaties",
                to="organisaties.LokaleOverheid",
                verbose_name="lokale overheid",
            ),
        ),
    ]
