# Generated by Django 2.2.24 on 2021-10-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0002_auto_20210927_1722"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lokaleoverheid",
            name="lau_code",
        ),
    ]
