# Generated by Django 2.2.24 on 2021-10-07 12:51

from django.db import migrations, models
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0003_auto_20211006_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokatie",
            name="dinsdag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="dinsdag",
            ),
        ),
        migrations.AddField(
            model_name="lokatie",
            name="donderdag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="donderdag",
            ),
        ),
        migrations.AddField(
            model_name="lokatie",
            name="maandag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="maandag",
            ),
        ),
        migrations.AddField(
            model_name="lokatie",
            name="vrijdag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="vrijdag",
            ),
        ),
        migrations.AddField(
            model_name="lokatie",
            name="woensdag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="woensdag",
            ),
        ),
        migrations.AddField(
            model_name="lokatie",
            name="zaterdag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="zaterdag",
            ),
        ),
        migrations.AddField(
            model_name="lokatie",
            name="zondag_tmp",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=32,
                    validators=[sdg.core.models.validators.validate_openingstijden],
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="zondag",
            ),
        ),
    ]
