# Generated by Django 2.2.24 on 2021-10-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0003_remove_lokaleoverheid_lau_code"),
        ("organisaties", "0006_post_data_migration"),
    ]

    operations = []
