# Generated by Django 2.2.24 on 2021-12-07 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0012_auto_20211108_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokaleoverheid",
            name="automatisch_catalogus_aanmaken",
            field=models.BooleanField(
                default=True,
                help_text="Indien aangevinkt wordt een specifieke catalogus aangemaakt voor deze lokale overheid.",
                verbose_name="Automatisch catalogus aanmaken",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="De identificatie die binnen deze API gebruikt wordt voor de resource.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="lokatie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="De identificatie die binnen deze API gebruikt wordt voor de resource.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
