# Generated by Django 2.2.24 on 2021-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0013_auto_20211207_1753"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokatie",
            name="openingstijden_opmerking",
            field=models.CharField(
                blank=True,
                help_text="Opmerking over de openingstijden.",
                max_length=255,
                verbose_name="openingstijden opmerking",
            ),
        ),
    ]
