# Generated by Django 2.2.24 on 2022-01-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0015_auto_20220122_1551"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="bevoegde_organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="Bevoegd gezag verantwoordelijk voor de procedure.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bevoegde",
                to="core.Overheidsorganisatie",
                verbose_name="bevoegde organisatie",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="ondersteunings_organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="organisatie voor ondersteuning.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ondersteunings",
                to="core.Overheidsorganisatie",
                verbose_name="ondersteunings organisatie",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="organisatie",
            field=models.ForeignKey(
                help_text="De organisatie van de lokale overheid.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisatie",
                to="core.Overheidsorganisatie",
                verbose_name="organisatie",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="verantwoordelijke_organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisatie verantwoordelijk voor de decentrale informatie.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verantwoordelijke",
                to="core.Overheidsorganisatie",
                verbose_name="verantwoordelijke organisatie",
            ),
        ),
    ]
