# Generated by Django 2.2.25 on 2022-04-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0017_auto_20220324_1221"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lokaleoverheid",
            name="contact_naam",
        ),
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="lokale_overheid",
            field=models.ForeignKey(
                help_text="De bij de overheid bekende naam van de bevoegde organisatie.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bevoegde_organisaties",
                to="organisaties.LokaleOverheid",
                verbose_name="lokale overheid",
            ),
        ),
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="naam",
            field=models.CharField(
                help_text="De naam van de bevoegde organisatie.",
                max_length=255,
                verbose_name="naam",
            ),
        ),
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="De organisatie van de bevoegde organisatie.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bevoegde_organisaties",
                to="core.Overheidsorganisatie",
                verbose_name="organisatie",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="ondersteunings_organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="organisatie voor ondersteuning.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ondersteunings",
                to="core.Overheidsorganisatie",
                verbose_name="ondersteunings organisatie",
            ),
        ),
    ]
