# Generated by Django 2.2.25 on 2022-04-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0018_auto_20220404_1610"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De naam van de bevoegde organisatie. Deze mag alleen afwijken indien er geen bekende overheidsorganisatie is.",
                max_length=255,
                verbose_name="naam",
            ),
        ),
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="organisatie",
            field=models.ForeignKey(
                blank=True,
                help_text="De bij de Rijksoverheid bekende organisatie die optreed als bevoegde organisatie.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bevoegde_organisaties",
                to="core.Overheidsorganisatie",
                verbose_name="organisatie",
            ),
        ),
    ]
