# Generated by Django 3.2.13 on 2022-05-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0020_auto_20220425_1911"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokatie",
            name="nummer",
            field=models.CharField(
                help_text="Het huisnummer van de locatie.",
                max_length=12,
                verbose_name="nummer",
            ),
        ),
    ]
