# Generated by Django 2.2.25 on 2022-05-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0020_auto_20220425_1911"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bevoegdeorganisatie",
            options={
                "ordering": ["naam", "lokale_overheid", "organisatie"],
                "verbose_name": "bevoegde organisatie",
                "verbose_name_plural": "bevoegde organisaties",
            },
        ),
        migrations.AlterModelOptions(
            name="lokaleoverheid",
            options={
                "ordering": ["organisatie"],
                "verbose_name": "lokale overheid",
                "verbose_name_plural": "lokale overheden",
            },
        ),
        migrations.AlterModelOptions(
            name="lokatie",
            options={
                "ordering": ["naam", "lokale_overheid"],
                "verbose_name": "locatie",
                "verbose_name_plural": "locaties",
            },
        ),
    ]
