# Generated by Django 3.2.13 on 2022-05-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0020_auto_20220425_1911"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bevoegdeorganisatie",
            options={
                "ordering": ["lokale_overheid__organisatie__owms_identifier"],
                "verbose_name": "bevoegde organisatie",
                "verbose_name_plural": "bevoegde organisaties",
            },
        ),
        migrations.AlterModelOptions(
            name="lokaleoverheid",
            options={
                "ordering": ["organisatie__owms_identifier"],
                "verbose_name": "lokale overheid",
                "verbose_name_plural": "lokale overheden",
            },
        ),
        migrations.AlterModelOptions(
            name="lokatie",
            options={
                "ordering": ["lokale_overheid__organisatie__owms_identifier"],
                "verbose_name": "locatie",
                "verbose_name_plural": "locaties",
            },
        ),
    ]
