# Generated by Django 3.2.13 on 2022-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0022_auto_20220622_1420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokatie",
            name="naam",
            field=models.CharField(
                help_text="De naam van de locatie.", max_length=100, verbose_name="naam"
            ),
        ),
    ]
