# Generated by Django 3.2.13 on 2022-07-07 15:09

import re
from django.db import migrations


def add_recursion_number(new_bevoegde_organisaties_lijst, organisatie_naam):
    if list(
        filter(
            lambda x: str(organisatie_naam) in str(x.naam),
            new_bevoegde_organisaties_lijst,
        )
    ):
        if re.search("( - )([0-9]*)$", organisatie_naam):
            bevoegde_naam, recursion_number = organisatie_naam.rsplit(" - ", 1)
            new_organisatie_naam = f"{bevoegde_naam} - {int(recursion_number) + 1}"

            return add_recursion_number(
                new_bevoegde_organisaties_lijst, new_organisatie_naam
            )
        else:
            new_organisatie_naam = f"{organisatie_naam} - 1"

            return add_recursion_number(
                new_bevoegde_organisaties_lijst, new_organisatie_naam
            )

    return organisatie_naam


def update_duplicate_names(apps, schema_editor):
    bevoegde_organisaties = apps.get_model("organisaties", "bevoegdeorganisatie")
    new_bevoegde_organisaties_lijst = []

    for organisatie in bevoegde_organisaties.objects.all().order_by("naam", "id"):
        naam = add_recursion_number(new_bevoegde_organisaties_lijst, organisatie.naam)

        new_bevoegde_organisaties_lijst.append(
            bevoegde_organisaties(
                pk=organisatie.pk,
                uuid=organisatie.uuid,
                naam=naam,
            )
        )

    bevoegde_organisaties.objects.bulk_update(new_bevoegde_organisaties_lijst, ["naam"])


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0023_alter_lokatie_naam"),
    ]

    operations = [
        migrations.RunPython(update_duplicate_names, migrations.RunPython.noop),
    ]
