# Generated by Django 3.2.13 on 2022-07-07 15:09

import re
from django.db import migrations
from django.db.models import Count


def update_duplicate_names(apps, schema_editor):
    BevoegdeOrganisatie = apps.get_model("organisaties", "bevoegdeorganisatie")
    new_bevoegde_organisaties_lijst = []

    duplicates = (
        BevoegdeOrganisatie.objects.values("naam")
        .annotate(Count("id"))
        .values("naam")
        .order_by()
        .filter(id__count__gt=1)
    )

    for organisatie in BevoegdeOrganisatie.objects.filter(naam__in=duplicates):

        new_bevoegde_organisaties_lijst.append(
            BevoegdeOrganisatie(
                pk=organisatie.pk,
                uuid=organisatie.uuid,
                naam=f"{organisatie.naam} - {organisatie.pk}",
            )
        )

    BevoegdeOrganisatie.objects.bulk_update(new_bevoegde_organisaties_lijst, ["naam"])


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0023_alter_lokatie_naam"),
    ]

    operations = [
        migrations.RunPython(update_duplicate_names, migrations.RunPython.noop),
    ]
