# Generated by Django 3.2.13 on 2022-07-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0024_update_duplicatie_bevoegde_organisatie_namen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De naam van de bevoegde organisatie. Deze mag alleen afwijken indien er geen bekende overheidsorganisatie is.",
                max_length=255,
                unique=True,
                verbose_name="naam",
            ),
        ),
    ]
