# Generated by Django 3.2.13 on 2022-07-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0025_alter_bevoegdeorganisatie_naam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="contact_emailadres",
            field=models.EmailField(
                blank=True,
                help_text="Het algemene e-mailadres van de organisatie of het e-mailadres van het klantcontactcentrum van de organisatie.",
                max_length=254,
                verbose_name="contact emailadres",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="contact_telefoonnummer",
            field=models.CharField(
                blank=True,
                help_text="Het internationale telefoonnummer waarop de organisatie bereikbaar is. Bijvoorbeeld: +31 20 624 1111",
                max_length=20,
                verbose_name="contact telefoonnummer",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="contact_website",
            field=models.URLField(
                blank=True,
                help_text="Website van de organisatie.",
                verbose_name="contact website",
            ),
        ),
    ]
