# Generated by Django 3.2.13 on 2022-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0025_alter_bevoegdeorganisatie_naam"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokaleoverheid",
            name="contact_formulier_link",
            field=models.URLField(
                blank=True,
                help_text="De webpagina van het contact formulier van de organisatie.",
                verbose_name="contact formulier",
            ),
        ),
    ]
