# Generated by Django 3.2.13 on 2022-08-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0026_auto_20220722_1002"),
        ("organisaties", "0026_lokaleoverheid_contact_formulier_link"),
    ]

    operations = []
