# Generated by Django 3.2.13 on 2022-08-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0027_merge_20220802_1442"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lokaleoverheid",
            name="ondersteunings_organisatie",
        ),
        migrations.AlterUniqueTogether(
            name="lokatie",
            unique_together={("naam", "lokale_overheid")},
        ),
    ]
