# Generated by Django 3.2.13 on 2022-09-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0028_auto_20220823_1518"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bevoegdeorganisatie",
            name="naam",
            field=models.CharField(
                blank=True,
                help_text="De naam van de bevoegde organisatie. Deze mag alleen afwijken indien er geen bekende overheidsorganisatie is.",
                max_length=255,
                verbose_name="naam",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bevoegdeorganisatie",
            unique_together={("naam", "lokale_overheid")},
        ),
    ]
