# Generated by Django 3.2.16 on 2022-12-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0029_auto_20220909_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lokaleoverheid",
            options={
                "ordering": ("organisatie__owms_identifier",),
                "verbose_name": "lokale overheid",
                "verbose_name_plural": "lokale overheden",
            },
        ),
        migrations.AlterModelOptions(
            name="lokatie",
            options={
                "ordering": ("naam",),
                "verbose_name": "locatie",
                "verbose_name_plural": "locaties",
            },
        ),
    ]
