# Generated by Django 3.2.16 on 2023-03-31 15:11

from django.db import migrations, models
import sdg.producten.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0030_auto_20221207_1855"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="contact_formulier_link",
            field=models.URLField(
                blank=True,
                help_text="De webpagina van het contact formulier van de organisatie.",
                validators=[sdg.producten.models.validators.validate_https],
                verbose_name="contact formulier",
            ),
        ),
        migrations.AlterField(
            model_name="lokaleoverheid",
            name="contact_website",
            field=models.URLField(
                blank=True,
                help_text="Website van de organisatie.",
                validators=[sdg.producten.models.validators.validate_https],
                verbose_name="contact website",
            ),
        ),
    ]
