# Generated by Django 3.2.16 on 2023-03-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organisaties", "0031_auto_20230331_1511"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE organisaties_lokaleoverheid \
            SET contact_formulier_link = REPLACE(contact_formulier_link, 'http', 'https') \
            WHERE contact_formulier_link LIKE 'http:%';"
        ),
        migrations.RunSQL(
            "UPDATE organisaties_lokaleoverheid \
            SET contact_website = REPLACE(contact_website, 'http', 'https') \
            WHERE contact_website LIKE 'http:%';"
        ),
    ]
