# Generated by Django 3.2.23 on 2024-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisaties', '0032_alter_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lokatie',
            options={'ordering': ('order', 'naam'), 'verbose_name': 'locatie', 'verbose_name_plural': 'locaties'},
        ),
        migrations.AddField(
            model_name='lokatie',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
