# # Generated by Django 2.2.24 on 2022-01-22 15:16

# from django.db import migrations, models
# import sdg.core.db.fields
# import sdg.core.models.validators
# import uuid


# class Migration(migrations.Migration):

#     dependencies = [
#         ('organisaties', '0014_lokatie_openingstijden_opmerking'),
#         ('producten', '0018_auto_20220119_1539'),
#     ]

#     operations = [
#         migrations.RenameModel('Lokatie', 'Locatie'),
#     ]
