# Generated by Django 3.2.13 on 2022-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_tokenauthorization"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Wanneer het token voor het laatst gebruikt is in de api.",
                null=True,
                verbose_name="laatst gekeken",
            ),
        ),
    ]
