# Generated by Django 3.2.13 on 2022-08-12 08:21

from django.db import migrations, models
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_token_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="whitelisted_ips",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(max_length=15),
                blank=True,
                default=list,
                help_text="De IP adressen waar organisaties onveilige API calls van mogen maken",
                size=None,
                validators=[sdg.core.models.validators.validate_ip_adress],
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="last_seen",
            field=models.DateTimeField(
                blank=True,
                help_text="Wanneer het token voor het laatst gebruikt is in de API.",
                null=True,
                verbose_name="laatste verzoek",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Wanneer het token voor het laatst is gewijzigd.",
                verbose_name="aangepast",
            ),
        ),
    ]
