# Generated by Django 3.2.13 on 2022-08-12 16:05

from django.db import migrations, models
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20220812_0821"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="whitelisted_ips",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(max_length=15),
                blank=True,
                default=list,
                help_text="De IP adressen waarvan organisaties POST, UPDATE en DELETE API calls van kan maken met deze API token.",
                size=None,
                validators=[sdg.core.models.validators.validate_ip_adress],
            ),
        ),
    ]
