# Generated by Django 3.2.13 on 2022-08-18 15:24

import django.core.validators
from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20220816_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="whitelisted_ips",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(
                    max_length=15,
                    validators=[django.core.validators.validate_ipv4_address],
                ),
                blank=True,
                default=list,
                help_text="Whitelisted IP adressen van deze token.",
                size=None,
            ),
        ),
    ]
