# Generated by Django 3.2.13 on 2022-09-22 12:47

import django.core.validators
from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_token_whitelisted_ips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="email",
            field=models.EmailField(
                help_text="E-mail van de contactpersoon",
                max_length=254,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="token",
            name="whitelisted_ips",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(
                    max_length=15,
                    validators=[django.core.validators.validate_ipv4_address],
                ),
                blank=True,
                default=list,
                help_text="Whitelisted IP adressen van deze token.",
                size=None,
            ),
        ),
    ]
