# Generated by Django 3.2.16 on 2022-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_auto_20220922_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="api_default_most_recent",
            field=models.BooleanField(
                default=False,
                help_text="Toon standaard de meest recente productbeschrijvingen in de API. Dit kunnen dus ook concept en toekomstige productbeschrijvingen zijn. Dit moet aan staan indien schrijfrechten op de API worden gegeven.",
                verbose_name="Standaard meest recent",
            ),
        ),
    ]
