# # Generated by Django 2.2.24 on 2022-01-22 15:16

# from django.db import migrations, models
# import sdg.producten.models.fields
# import uuid


# class Migration(migrations.Migration):

#     dependencies = [
#         ('organisaties', '0015_auto_20220122_1516'),
#         ('producten', '0018_auto_20220119_1539'),
#     ]

#     operations = [
#         migrations.RenameField(model_name='product', old_name='lokaties', new_name='locaties'),
#         migrations.AlterField(
#             model_name='localizedgeneriekproduct',
#             name='generieke_tekst',
#             field=sdg.producten.models.fields.MarkdownxField(help_text='De Nationale Portalen schrijven een inleidende, algemene tekst over het product. Het idee is dat deze ', verbose_name='generieke tekst'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='bewijs',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Bewijs (type/format).', verbose_name='bewijs'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='bezwaar_en_beroep',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Bezwaar en beroep.', verbose_name='bezwaar en beroep'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='kosten_en_betaalmethoden',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Kosten en betaalmethoden.', verbose_name='kosten en betaalmethoden'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='procedure_beschrijving',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Procedurebeschrijving.', verbose_name='procedure beschrijving'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='specifieke_tekst',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Decentrale omschrijving.', verbose_name='specifieke tekst'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='uiterste_termijn',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Deadlines.', verbose_name='uiterste termijn'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='vereisten',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Vereisten auth/id/sign.', verbose_name='vereisten'),
#         ),
#         migrations.AlterField(
#             model_name='localizedproduct',
#             name='wtd_bij_geen_reactie',
#             field=sdg.producten.models.fields.MarkdownxField(blank=True, help_text='Wat te doen bij geen reactie.', verbose_name='wtd bij geen reactie'),
#         ),
#         migrations.AlterField(
#             model_name='product',
#             name='product_aanwezig',
#             field=models.BooleanField(blank=True, help_text='Voert u dit product?', null=True, verbose_name='aanwezig'),
#         ),
#         migrations.AlterField(
#             model_name='product',
#             name='product_aanwezig_toelichting',
#             field=models.TextField(blank=True, default='', help_text='Toelichting', verbose_name='aanwezig toelichting'),
#         ),
#         migrations.AlterField(
#             model_name='product',
#             name='uuid',
#             field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='De identificatie die binnen deze API gebruikt wordt voor de resource.', unique=True, verbose_name='UUID'),
#         ),
#     ]
