# # Generated by Django 2.2.24 on 2022-01-22 15:30

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('producten', '0019_auto_20220122_1516'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='product',
#             name='locaties',
#             field=models.ManyToManyField(blank=True, help_text='De locaties die zijn toegewezen aan de product.', related_name='producten', to='organisaties.Locatie', verbose_name='locaties'),
#         ),
#         # migrations.RenameField(model_name='producten_product_locaties', old_name='lokatie_id', new_name='locatie_id')
#         migrations.RunSQL('ALTER TABLE "producten_product_locaties" RENAME COLUMN "lokatie_id" TO "locatie_id";')
#     ]
