# Generated by Django 2.2.24 on 2021-08-25 10:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import sdg.core.db.fields
import sdg.core.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Informatiegebied",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De code van het desbetreffende informatiegebied.",
                        max_length=3,
                        verbose_name="code",
                    ),
                ),
                (
                    "informatiegebied",
                    models.CharField(
                        help_text="Het bij de gegevens behorende informatiegebied.",
                        max_length=40,
                        verbose_name="informatiegebied",
                    ),
                ),
            ],
            options={
                "verbose_name": "informatiegebied",
                "verbose_name_plural": "informatiegebieden",
            },
        ),
        migrations.CreateModel(
            name="LokaleOverheid",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_naam",
                    models.CharField(
                        help_text="De naam van de verantwoordelijke contactpersoon.",
                        max_length=40,
                        verbose_name="contact naam",
                    ),
                ),
                (
                    "contact_website",
                    models.URLField(
                        blank=True,
                        help_text="De website van de verantwoordelijke contactpersoon.",
                        null=True,
                        verbose_name="contact website",
                    ),
                ),
                (
                    "contact_telefoonnummer",
                    models.CharField(
                        blank=True,
                        help_text="Het telefoonnummer van de verantwoordelijke contactpersoon.",
                        max_length=20,
                        null=True,
                        verbose_name="contact telefoonnummer",
                    ),
                ),
                (
                    "contact_emailadres",
                    models.EmailField(
                        blank=True,
                        help_text="Het e-mailadres van de verantwoordelijke contactpersoon.",
                        max_length=254,
                        null=True,
                        verbose_name="contact emailadres",
                    ),
                ),
            ],
            options={
                "verbose_name": "lokale overheid",
                "verbose_name_plural": "lokale overheden",
            },
        ),
        migrations.CreateModel(
            name="Lokatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lokatie_adres",
                    models.TextField(
                        help_text="De gegevens over het adres van de lokatie.",
                        max_length=1000,
                        verbose_name="lokatie adres",
                    ),
                ),
                (
                    "lokale_overheid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.LokaleOverheid",
                        verbose_name="lokale overheid",
                    ),
                ),
            ],
            options={
                "verbose_name": "lokatie",
                "verbose_name_plural": "lokaties",
            },
        ),
        migrations.CreateModel(
            name="Overheidsorganisatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owms_identifier",
                    models.URLField(
                        help_text="De metadatastandaard voor informatie van de nederlandse overheid op internet.",
                        verbose_name="owms identifier",
                    ),
                ),
                (
                    "owms_pref_label",
                    models.CharField(
                        help_text="De wettelijk erkende naam van de organisatie.",
                        max_length=80,
                        verbose_name="owms pref label",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van de overheidsorganisatie.",
                        max_length=40,
                        verbose_name="naam",
                    ),
                ),
            ],
            options={
                "verbose_name": "overheidsorganisatie",
                "verbose_name_plural": "overheidsorganisaties",
            },
        ),
        migrations.CreateModel(
            name="ProductenCatalogus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domein",
                    models.CharField(
                        help_text="Een afkorting die wordt gebruikt om het domein aan te duiden.",
                        max_length=5,
                        validators=[sdg.core.models.validators.validate_uppercase],
                        verbose_name="domein",
                    ),
                ),
                (
                    "versie",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Het versienummer van het producten catalogus.",
                        verbose_name="versie",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van de producten catalogus.",
                        max_length=40,
                        verbose_name="naam",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Toelichting bij het catalogus.",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "lokale_overheid",
                    models.ForeignKey(
                        blank=True,
                        help_text="De lokale overheid die bij deze catalogus hoort.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalogi",
                        to="core.LokaleOverheid",
                        verbose_name="lokale overheid",
                    ),
                ),
                (
                    "referentie_catalogus",
                    models.ForeignKey(
                        blank=True,
                        help_text="De catalogus van referentie.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.ProductenCatalogus",
                        verbose_name="referentie catalogus",
                    ),
                ),
            ],
            options={
                "verbose_name": "producten catalogus",
                "verbose_name_plural": "productcatalogi",
            },
        ),
        migrations.CreateModel(
            name="ProductGeneriekInformatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taal",
                    models.CharField(
                        choices=[("NL", "Nederlands"), ("EN", "Engels")],
                        help_text="De taal waarin de betreffende tekst is geschreven.ISO 639 (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)",
                        max_length=3,
                        verbose_name="taal",
                    ),
                ),
                (
                    "product_titel",
                    models.CharField(
                        help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                        max_length=50,
                        verbose_name="product titel",
                    ),
                ),
                (
                    "generieke_tekst",
                    markdownx.models.MarkdownxField(
                        help_text="De Nationale Portalen schrijven een inleidende, algemene tekst over het product. Het idee is dat deze ",
                        verbose_name="generieke tekst",
                    ),
                ),
                (
                    "korte_omschrijving",
                    models.CharField(
                        help_text='Korte omschrijving van wat er op de pagina staat, gebruikt in de meta tags van de productpagina (meta name="description"). Deze tekst wordt gebruikt om te tonen wanneer de pagina wordt gevonden in een zoekmachine. ',
                        max_length=80,
                        verbose_name="korte omschrijving",
                    ),
                ),
                (
                    "datum_check",
                    models.DateTimeField(
                        help_text="De informatie over het product kan worden gewijzigd en gecontroleerd op actualiteit (gecheckt). De Nationale portalen houden bij wanneer de informatie voor het laasts is 'gecheckt'.  Deze datum wordt op het portaal getoond.",
                        verbose_name="datum check",
                    ),
                ),
                (
                    "verwijzing_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="url van verwijzing"
                        ),
                        blank=True,
                        default=list,
                        help_text="Zowel de Nationale Portalen als de decentrale overheden kunnen een x-tal 'verwijzingen' opnemen bij een product. Voorstel hierbij om zo'n 'verwijzing' te laten bestaan uit een -bij elkaar horende-  beschrijving en hyperlink. De tekst van artikel 9 geeft enkele voorbeelden hiervan: 'richtsnoeren/ NEN-specs bijv en ook links naar de wetgeving (dit laatste is inderdaad te verstaan als vertaling van 'Legal Acts'. Bart heeft dit bij Jurist van bNC (Vanessa) gecheckt. ",
                        size=None,
                    ),
                ),
                (
                    "landelijke_link",
                    models.URLField(
                        help_text="URL van de productpagina wanneer het een landelijk product betreft of de pagina met enkel generieke beschrijving van een decentraal product, bijvoorbeeld : https://ondernemersplein.kvk.nl/terrasvergunning. gebruikt voor o.a. notificeren, feedback & statistics en het kunnen bekijken van de generieke productinformatie (bv door gebruikers van de gemeentelijke invoervoorziening) ",
                        verbose_name="landelijke link",
                    ),
                ),
                (
                    "verplicht_product",
                    models.BooleanField(
                        help_text="Geeft aan of decentrale overheden verplicht zijn informatie over dit product te leveren.",
                        verbose_name="verplicht product",
                    ),
                ),
                (
                    "generieke_link",
                    models.URLField(
                        help_text="URL van de productpagina wanneer het een landelijk product betreft of de pagina met enkel generieke beschrijving van een decentraal product, bijvoorbeeld : https://ondernemersplein.kvk.nl/terrasvergunning. gebruikt voor o.a. notificeren, feedback & statistics en het kunnen bekijken van de generieke productinformatie (bv door gebruikers van de gemeentelijke invoervoorziening) ",
                        verbose_name="generieke link",
                    ),
                ),
            ],
            options={
                "verbose_name": "product generiek informatie",
                "verbose_name_plural": "product generiek informatie",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecifiekAanvraag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_beschrijving",
                    markdownx.models.MarkdownxField(
                        help_text="Procedurebeschrijving.",
                        verbose_name="procedure beschrijving",
                    ),
                ),
                (
                    "vereisten",
                    markdownx.models.MarkdownxField(
                        help_text="Vereisten auth/id/sign.", verbose_name="vereisten"
                    ),
                ),
                (
                    "bewijs",
                    markdownx.models.MarkdownxField(
                        help_text="Bewijs (type/format).", verbose_name="bewijs"
                    ),
                ),
                (
                    "bezwaar_en_beroep",
                    markdownx.models.MarkdownxField(
                        help_text="Bezwaar en beroep.", verbose_name="bezwaar en beroep"
                    ),
                ),
                (
                    "kosten_en_betaalmethoden",
                    markdownx.models.MarkdownxField(
                        help_text="Kosten en betaalmethoden.",
                        verbose_name="kosten en betaalmethoden",
                    ),
                ),
                (
                    "uiterste_termijn",
                    markdownx.models.MarkdownxField(
                        help_text="Deadlines.", verbose_name="uiterste termijn"
                    ),
                ),
                (
                    "wtd_bij_geen_reactie",
                    markdownx.models.MarkdownxField(
                        help_text="Wat te doen bij geen reactie.",
                        verbose_name="wtd bij geen reactie",
                    ),
                ),
                (
                    "decentrale_procedure_link",
                    models.URLField(
                        help_text="Link naar de procedure voor burgers en / of bedrijven.",
                        verbose_name="decentrale procedure link",
                    ),
                ),
                (
                    "lokaties",
                    models.ManyToManyField(
                        help_text="De locaties die zijn toegewezen aan de productaanvraag.",
                        related_name="productaanvragen",
                        to="core.Lokatie",
                        verbose_name="lokaties",
                    ),
                ),
            ],
            options={
                "verbose_name": "product specifiek aanvraag",
                "verbose_name_plural": "product specifiek aanvragen",
            },
        ),
        migrations.CreateModel(
            name="ProductSpecifiekInformatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_titel_decentraal",
                    models.CharField(
                        help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                        max_length=50,
                        verbose_name="product titel decentraal",
                    ),
                ),
                (
                    "specifieke_tekst",
                    markdownx.models.MarkdownxField(
                        help_text="Decentrale omschrijving.",
                        verbose_name="specifieke tekst",
                    ),
                ),
                (
                    "verwijzing_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="url van verwijzing"
                        ),
                        blank=True,
                        default=list,
                        help_text="Decentrale verwijzingen.",
                        size=None,
                    ),
                ),
                (
                    "specifieke_link",
                    models.URLField(
                        help_text="URL decentrale productpagina.",
                        verbose_name="specifieke link",
                    ),
                ),
                (
                    "decentrale_link",
                    models.URLField(
                        help_text="Link naar decentrale productpagina voor burgers en / of bedrijven.",
                        verbose_name="decentrale link",
                    ),
                ),
                (
                    "datum_wijziging",
                    models.DateTimeField(
                        help_text="Decentrale overheden geven een wijzigingsdatum mee voor hun informatie. Deze datum wordt op het portaal getoond. ",
                        verbose_name="datum wijziging",
                    ),
                ),
                (
                    "doelgroep",
                    sdg.core.db.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("burgers", "Burgers"),
                                ("bedrijven", "Bedrijven"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                        help_text="Geeft aan voor welke doelgroep het product is bedoeld: burgers, bedrijven of burgers en bedrijven. Wordt gebruikt wanneer een portaal informatie over het product ophaalt uit de invoervoorziening. Zo krijgen de ondernemersportalen de ondernemersvariant en de burgerportalen de burgervariant. ",
                        size=None,
                    ),
                ),
                (
                    "beschikbaar",
                    models.BooleanField(
                        help_text="Geeft aan of het product al dan niet beschikbaar is.",
                        verbose_name="beschikbaar",
                    ),
                ),
                (
                    "versie",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Het versienummer van het item.",
                        verbose_name="versie",
                    ),
                ),
                (
                    "publicatie_datum",
                    models.DateTimeField(
                        help_text="De datum van publicatie van de productspecifieke informatie.",
                        verbose_name="publicatie datum",
                    ),
                ),
                (
                    "catalogus",
                    models.ForeignKey(
                        help_text="Referentie naar de catalogus waartoe dit product behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="producten",
                        to="core.ProductenCatalogus",
                        verbose_name="product specifiek informatie",
                    ),
                ),
                (
                    "generiek_product",
                    models.OneToOneField(
                        help_text="Een verwijzing naar de generieke versie van dit product",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="specifiek_product",
                        to="core.ProductGeneriekInformatie",
                        verbose_name="generiek product",
                    ),
                ),
                (
                    "gerelateerd_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Een verwijzing naar een gerelateerd product.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gerelateerd",
                        to="core.ProductSpecifiekInformatie",
                        verbose_name="gerelateerd aan",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        blank=True,
                        help_text="Een verwijzing naar een ander product.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gerefereerd",
                        to="core.ProductSpecifiekInformatie",
                        verbose_name="refereert aan",
                    ),
                ),
            ],
            options={
                "verbose_name": "product specifiek informatie",
                "verbose_name_plural": "product specifiek informatie",
            },
        ),
        migrations.CreateModel(
            name="StandaardProductSpecifiekAanvraag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_beschrijving",
                    markdownx.models.MarkdownxField(
                        help_text="Procedurebeschrijving.",
                        verbose_name="procedure beschrijving",
                    ),
                ),
                (
                    "vereisten",
                    markdownx.models.MarkdownxField(
                        help_text="Vereisten auth/id/sign.", verbose_name="vereisten"
                    ),
                ),
                (
                    "bewijs",
                    markdownx.models.MarkdownxField(
                        help_text="Bewijs (type/format).", verbose_name="bewijs"
                    ),
                ),
                (
                    "bezwaar_en_beroep",
                    markdownx.models.MarkdownxField(
                        help_text="Bezwaar en beroep.", verbose_name="bezwaar en beroep"
                    ),
                ),
                (
                    "kosten_en_betaalmethoden",
                    markdownx.models.MarkdownxField(
                        help_text="Kosten en betaalmethoden.",
                        verbose_name="kosten en betaalmethoden",
                    ),
                ),
                (
                    "uiterste_termijn",
                    markdownx.models.MarkdownxField(
                        help_text="Deadlines.", verbose_name="uiterste termijn"
                    ),
                ),
                (
                    "wtd_bij_geen_reactie",
                    markdownx.models.MarkdownxField(
                        help_text="Wat te doen bij geen reactie.",
                        verbose_name="wtd bij geen reactie",
                    ),
                ),
                (
                    "decentrale_procedure_link",
                    models.URLField(
                        help_text="Link naar de procedure voor burgers en / of bedrijven.",
                        verbose_name="decentrale procedure link",
                    ),
                ),
            ],
            options={
                "verbose_name": "standaard product specifiek aanvraag",
                "verbose_name_plural": "standaard product specifiek aanvragen",
            },
        ),
        migrations.CreateModel(
            name="StandaardProductSpecifiekInformatie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_titel_decentraal",
                    models.CharField(
                        help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                        max_length=50,
                        verbose_name="product titel decentraal",
                    ),
                ),
                (
                    "specifieke_tekst",
                    markdownx.models.MarkdownxField(
                        help_text="Decentrale omschrijving.",
                        verbose_name="specifieke tekst",
                    ),
                ),
                (
                    "verwijzing_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="url van verwijzing"
                        ),
                        blank=True,
                        default=list,
                        help_text="Decentrale verwijzingen.",
                        size=None,
                    ),
                ),
                (
                    "specifieke_link",
                    models.URLField(
                        help_text="URL decentrale productpagina.",
                        verbose_name="specifieke link",
                    ),
                ),
                (
                    "decentrale_link",
                    models.URLField(
                        help_text="Link naar decentrale productpagina voor burgers en / of bedrijven.",
                        verbose_name="decentrale link",
                    ),
                ),
                (
                    "datum_wijziging",
                    models.DateTimeField(
                        help_text="Decentrale overheden geven een wijzigingsdatum mee voor hun informatie. Deze datum wordt op het portaal getoond. ",
                        verbose_name="datum wijziging",
                    ),
                ),
            ],
            options={
                "verbose_name": "standaard product specifiek informatie",
                "verbose_name_plural": "standaard product specifiek informatie",
            },
        ),
        migrations.CreateModel(
            name="StandaardProductuitvoering",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_titel_decentraal",
                    models.CharField(
                        help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                        max_length=50,
                        verbose_name="product titel decentraal",
                    ),
                ),
                (
                    "specifieke_tekst",
                    markdownx.models.MarkdownxField(
                        help_text="Decentrale omschrijving.",
                        verbose_name="specifieke tekst",
                    ),
                ),
                (
                    "verwijzing_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="url van verwijzing"
                        ),
                        blank=True,
                        default=list,
                        help_text="Decentrale verwijzingen.",
                        size=None,
                    ),
                ),
                (
                    "specifieke_link",
                    models.URLField(
                        help_text="URL decentrale productpagina.",
                        verbose_name="specifieke link",
                    ),
                ),
                (
                    "decentrale_link",
                    models.URLField(
                        help_text="Link naar decentrale productpagina voor burgers en / of bedrijven.",
                        verbose_name="decentrale link",
                    ),
                ),
                (
                    "datum_wijziging",
                    models.DateTimeField(
                        help_text="Decentrale overheden geven een wijzigingsdatum mee voor hun informatie. Deze datum wordt op het portaal getoond. ",
                        verbose_name="datum wijziging",
                    ),
                ),
            ],
            options={
                "verbose_name": "standaard productuitvoering",
                "verbose_name_plural": "standaard productuitvoeringen",
            },
        ),
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De code van het desbetreffende thema.",
                        max_length=3,
                        verbose_name="code",
                    ),
                ),
                (
                    "thema",
                    models.CharField(
                        help_text="Het thema dat verband houdt met de gegevens.",
                        max_length=40,
                        verbose_name="thema",
                    ),
                ),
                (
                    "informatiegebied",
                    models.OneToOneField(
                        help_text="Het informatiegebied met betrekking tot dit thema.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="thema",
                        to="core.Informatiegebied",
                        verbose_name="informatiegebied",
                    ),
                ),
            ],
            options={
                "verbose_name": "thema",
                "verbose_name_plural": "thema's",
            },
        ),
        migrations.CreateModel(
            name="UniformeProductnaam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upn_uri",
                    models.URLField(
                        help_text="Uniforme Productnaam URI van landelijk product",
                        verbose_name="UPN URI",
                    ),
                ),
                (
                    "upn_label",
                    models.CharField(
                        help_text="Het bijbehorende label. Zie https://standaarden.overheid.nl/owms/oquery/UPL-actueel.plain voor de volledige UPL. ",
                        max_length=255,
                        verbose_name="UPN label",
                    ),
                ),
                (
                    "thema",
                    models.ForeignKey(
                        help_text="Het informatiegebied met betrekking tot dit thema.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upn",
                        to="core.Thema",
                        verbose_name="thema",
                    ),
                ),
            ],
            options={
                "verbose_name": "uniforme productnaam",
                "verbose_name_plural": "uniforme productnamen",
            },
        ),
        migrations.CreateModel(
            name="Productuitvoering",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_titel_decentraal",
                    models.CharField(
                        help_text="De titel van het decentrale product, die immers kan afwijken van de landelijke titel.",
                        max_length=50,
                        verbose_name="product titel decentraal",
                    ),
                ),
                (
                    "specifieke_tekst",
                    markdownx.models.MarkdownxField(
                        help_text="Decentrale omschrijving.",
                        verbose_name="specifieke tekst",
                    ),
                ),
                (
                    "verwijzing_links",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="url van verwijzing"
                        ),
                        blank=True,
                        default=list,
                        help_text="Decentrale verwijzingen.",
                        size=None,
                    ),
                ),
                (
                    "specifieke_link",
                    models.URLField(
                        help_text="URL decentrale productpagina.",
                        verbose_name="specifieke link",
                    ),
                ),
                (
                    "decentrale_link",
                    models.URLField(
                        help_text="Link naar decentrale productpagina voor burgers en / of bedrijven.",
                        verbose_name="decentrale link",
                    ),
                ),
                (
                    "datum_wijziging",
                    models.DateTimeField(
                        help_text="Decentrale overheden geven een wijzigingsdatum mee voor hun informatie. Deze datum wordt op het portaal getoond. ",
                        verbose_name="datum wijziging",
                    ),
                ),
                (
                    "product_titel_uitvoering",
                    models.CharField(
                        help_text="De titel van het  product, die immers kan afwijken van de landelijke titel.",
                        max_length=50,
                        verbose_name="product titel_uitovering",
                    ),
                ),
                (
                    "product_specifiek_aanvraag",
                    models.ForeignKey(
                        help_text="Referentie naar het product specifiek aanvraag.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ProductSpecifiekAanvraag",
                        verbose_name="product specifiek aanvraag",
                    ),
                ),
                (
                    "product_specifiek_informatie",
                    models.ForeignKey(
                        help_text="Referentie naar het product specifiek informatie.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.ProductSpecifiekInformatie",
                        verbose_name="product specifiek informatie",
                    ),
                ),
                (
                    "standaard",
                    models.ForeignKey(
                        help_text="De standaardinformatie voor de productuitvoering.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aanpassingen",
                        to="core.StandaardProductuitvoering",
                        verbose_name="standaard",
                    ),
                ),
            ],
            options={
                "verbose_name": "productuitvoering",
                "verbose_name_plural": "productuitvoeringen",
            },
        ),
        migrations.AddField(
            model_name="productspecifiekinformatie",
            name="standaard",
            field=models.ForeignKey(
                help_text="De standaardinformatie voor de product specifiek informatie.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aanpassingen",
                to="core.StandaardProductSpecifiekInformatie",
                verbose_name="standaard",
            ),
        ),
        migrations.AddField(
            model_name="productspecifiekaanvraag",
            name="specifiek_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifiek_aanvraag",
                to="core.ProductSpecifiekInformatie",
                verbose_name="specifiek product",
            ),
        ),
        migrations.AddField(
            model_name="productspecifiekaanvraag",
            name="standaard",
            field=models.ForeignKey(
                help_text="De standaardinformatie voor de product specifiek aanvraag.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aanpassingen",
                to="core.StandaardProductSpecifiekAanvraag",
                verbose_name="standaard",
            ),
        ),
        migrations.AddField(
            model_name="productgeneriekinformatie",
            name="upn",
            field=models.ForeignKey(
                help_text="De uniforme productnaam met betrekking tot dit product.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generiek_product",
                to="core.UniformeProductnaam",
                verbose_name="uniforme productnaam",
            ),
        ),
        migrations.AddField(
            model_name="productgeneriekinformatie",
            name="verantwoordelijke_organisatie",
            field=models.ForeignKey(
                help_text="Organisatie verantwoordelijk voor de landelijke informatie",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generiek_informatie",
                to="core.Overheidsorganisatie",
                verbose_name="verantwoordelijke organisatie",
            ),
        ),
        migrations.AddField(
            model_name="lokaleoverheid",
            name="bevoegde_organisatie",
            field=models.ForeignKey(
                help_text="Bevoegd gezag verantwoordelijk voor de procedure.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bevoegde",
                to="core.Overheidsorganisatie",
                verbose_name="bevoegde organisatie",
            ),
        ),
        migrations.AddField(
            model_name="lokaleoverheid",
            name="ondersteunings_organisatie",
            field=models.ForeignKey(
                help_text="Organisatie voor ondersteuning.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ondersteunings",
                to="core.Overheidsorganisatie",
                verbose_name="ondersteunings organisatie",
            ),
        ),
        migrations.AddField(
            model_name="lokaleoverheid",
            name="organisatie",
            field=models.ForeignKey(
                help_text="De organisatie van de lokale overheid.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organisatie",
                to="core.Overheidsorganisatie",
                verbose_name="organisatie",
            ),
        ),
        migrations.AddField(
            model_name="lokaleoverheid",
            name="verantwoordelijke_organisatie",
            field=models.ForeignKey(
                help_text="Organisatie verantwoordelijk voor de decentrale informatie.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verantwoordelijke",
                to="core.Overheidsorganisatie",
                verbose_name="verantwoordelijke organisatie",
            ),
        ),
    ]
