# Generated by Django 2.2.24 on 2021-08-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="overheidsorganisatie",
            name="naam",
        ),
        migrations.RemoveField(
            model_name="thema",
            name="code",
        ),
        migrations.AddField(
            model_name="informatiegebied",
            name="informatiegebied_uri",
            field=models.URLField(
                default="https://www.example.com",
                help_text="Informatiegebied URI van landelijk product",
                verbose_name="informatiegebied uri",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="overheidsorganisatie",
            name="owms_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="De endDate, zoals gevonden in het OWMS-model.",
                null=True,
                verbose_name="end date",
            ),
        ),
        migrations.AddField(
            model_name="thema",
            name="thema_uri",
            field=models.URLField(
                default="https://www.example.com",
                help_text="Thema URI van landelijk product",
                verbose_name="thema uri",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="aanvraag",
            field=models.BooleanField(default=False, verbose_name="aanvraag"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="autonomie",
            field=models.BooleanField(default=False, verbose_name="autonomie"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="bedrijf",
            field=models.BooleanField(default=False, verbose_name="bedrijf"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="burger",
            field=models.BooleanField(default=False, verbose_name="burger"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="dienstenwet",
            field=models.BooleanField(default=False, verbose_name="dienstenwet"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="digi_d_macht",
            field=models.BooleanField(default=False, verbose_name="digi_d_macht"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="gemeente",
            field=models.BooleanField(default=False, verbose_name="gemeente"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="grondslag",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="grondslag"
            ),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="grondslaglabel",
            field=models.CharField(
                blank=True, max_length=512, null=True, verbose_name="grondslaglabel"
            ),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="grondslaglink",
            field=models.URLField(blank=True, null=True, verbose_name="grondslaglink"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="medebewind",
            field=models.BooleanField(default=False, verbose_name="medebewind"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="melding",
            field=models.BooleanField(default=False, verbose_name="melding"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="provincie",
            field=models.BooleanField(default=False, verbose_name="provincie"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="rijk",
            field=models.BooleanField(default=False, verbose_name="rijk"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="sdg",
            field=models.BooleanField(default=False, verbose_name="sdg"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="subsidie",
            field=models.BooleanField(default=False, verbose_name="subsidie"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="verplichting",
            field=models.BooleanField(default=False, verbose_name="verplichting"),
        ),
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="waterschap",
            field=models.BooleanField(default=False, verbose_name="waterschap"),
        ),
        migrations.AlterField(
            model_name="informatiegebied",
            name="code",
            field=models.CharField(
                help_text="De code van het desbetreffende informatiegebied.",
                max_length=3,
                unique=True,
                verbose_name="code",
            ),
        ),
        migrations.AlterField(
            model_name="informatiegebied",
            name="informatiegebied",
            field=models.CharField(
                help_text="Het bij de gegevens behorende informatiegebied.",
                max_length=80,
                verbose_name="informatiegebied",
            ),
        ),
        migrations.AlterField(
            model_name="overheidsorganisatie",
            name="owms_identifier",
            field=models.URLField(
                help_text="De metadatastandaard voor informatie van de nederlandse overheid op internet.",
                unique=True,
                verbose_name="owms identifier",
            ),
        ),
        migrations.AlterField(
            model_name="thema",
            name="thema",
            field=models.CharField(
                help_text="Het thema dat verband houdt met de gegevens.",
                max_length=512,
                verbose_name="thema",
            ),
        ),
        migrations.AlterField(
            model_name="uniformeproductnaam",
            name="thema",
            field=models.ForeignKey(
                blank=True,
                help_text="Het informatiegebied met betrekking tot dit thema.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="upn",
                to="core.Thema",
                verbose_name="thema",
            ),
        ),
    ]
