# Generated by Django 2.2.24 on 2021-09-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("organisaties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productencatalogus",
            name="lokale_overheid",
            field=models.ForeignKey(
                help_text="De lokale overheid die bij deze catalogus hoort.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="catalogi",
                to="organisaties.LokaleOverheid",
                verbose_name="lokale overheid",
            ),
        ),
        migrations.AddField(
            model_name="productencatalogus",
            name="referentie_catalogus",
            field=models.ForeignKey(
                blank=True,
                help_text="De catalogus van referentie.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.ProductenCatalogus",
                verbose_name="referentie catalogus",
            ),
        ),
    ]
