# Generated by Django 2.2.24 on 2021-09-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20210922_1118"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productencatalogus",
            name="referentie_catalogus",
            field=models.ForeignKey(
                blank=True,
                help_text="De catalogus van referentie.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specifieke_catalogi",
                to="core.ProductenCatalogus",
                verbose_name="referentie catalogus",
            ),
        ),
    ]
