# Generated by Django 2.2.24 on 2021-08-31 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210827_1824"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productspecifiekaanvraag",
            name="lokaties",
        ),
        migrations.RemoveField(
            model_name="productspecifiekaanvraag",
            name="specifiek_product",
        ),
        migrations.RemoveField(
            model_name="productspecifiekaanvraag",
            name="standaard",
        ),
        migrations.RemoveField(
            model_name="productspecifiekinformatie",
            name="catalogus",
        ),
        migrations.RemoveField(
            model_name="productspecifiekinformatie",
            name="generiek_product",
        ),
        migrations.RemoveField(
            model_name="productspecifiekinformatie",
            name="gerelateerd_product",
        ),
        migrations.RemoveField(
            model_name="productspecifiekinformatie",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productspecifiekinformatie",
            name="standaard",
        ),
        migrations.RemoveField(
            model_name="productuitvoering",
            name="product_specifiek_aanvraag",
        ),
        migrations.RemoveField(
            model_name="productuitvoering",
            name="product_specifiek_informatie",
        ),
        migrations.RemoveField(
            model_name="productuitvoering",
            name="standaard",
        ),
        migrations.DeleteModel(
            name="ProductGeneriekInformatie",
        ),
        migrations.DeleteModel(
            name="ProductSpecifiekAanvraag",
        ),
        migrations.DeleteModel(
            name="ProductSpecifiekInformatie",
        ),
        migrations.DeleteModel(
            name="Productuitvoering",
        ),
        migrations.DeleteModel(
            name="StandaardProductSpecifiekAanvraag",
        ),
        migrations.DeleteModel(
            name="StandaardProductSpecifiekInformatie",
        ),
        migrations.DeleteModel(
            name="StandaardProductuitvoering",
        ),
    ]
