# Generated by Django 2.2.24 on 2021-08-31 10:41

from django.db import migrations, models
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20210831_1116"),
    ]

    operations = [
        migrations.AddField(
            model_name="lokaleoverheid",
            name="lau_code",
            field=models.CharField(
                blank=True,
                help_text="Een geldige LAU-code van de organisatie.",
                max_length=5,
                null=True,
                validators=[sdg.core.models.validators.validate_lau],
                verbose_name="LAU-code",
            ),
        ),
    ]
