# Generated by Django 2.2.24 on 2021-10-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210929_1649"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uniformeproductnaam",
            name="grondslag",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="grondslag"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uniformeproductnaam",
            name="grondslaglabel",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="grondslaglabel"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uniformeproductnaam",
            name="grondslaglink",
            field=models.URLField(blank=True, default="", verbose_name="grondslaglink"),
            preserve_default=False,
        ),
    ]
