# Generated by Django 2.2.24 on 2021-10-28 17:03

from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20211012_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="productencatalogus",
            name="autofill",
            field=models.BooleanField(default=False, verbose_name="autofill"),
        ),
        migrations.AddField(
            model_name="productencatalogus",
            name="autofill_upn_filter",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=models.CharField(max_length=80, verbose_name="filter"),
                blank=True,
                default=list,
                help_text="autofill upn filter",
                size=None,
            ),
        ),
    ]
