# Generated by Django 2.2.24 on 2021-11-08 15:54

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    ProductenCatalogus = apps.get_model("core", "ProductenCatalogus")
    for obj in ProductenCatalogus.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_productencatalogus_uuid"),
    ]

    operations = [
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="productencatalogus",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
