# Generated by Django 2.2.24 on 2021-11-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20211108_1554"),
        ("core", "0008_auto_20211028_1703"),
    ]

    operations = []
