# Generated by Django 2.2.24 on 2021-11-29 15:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merge_20211116_1604"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productencatalogus",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="De identificatie die binnen deze API gebruikt wordt voor de resource.",
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="thema",
            name="informatiegebied",
            field=models.ForeignKey(
                help_text="Het informatiegebied met betrekking tot dit thema.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="thema",
                to="core.Informatiegebied",
                verbose_name="informatiegebied",
            ),
        ),
        migrations.AlterField(
            model_name="thema",
            name="thema_uri",
            field=models.URLField(
                help_text="Thema URI van landelijk product",
                unique=True,
                verbose_name="thema uri",
            ),
        ),
        migrations.AddConstraint(
            model_name="uniformeproductnaam",
            constraint=models.UniqueConstraint(
                fields=("upn_uri", "grondslag"), name="unique_upn_uri_and_grondslag"
            ),
        ),
    ]
