# Generated by Django 2.2.24 on 2021-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_auto_20211128_1317"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="uniformeproductnaam",
            name="unique_upn_uri_and_grondslag",
        ),
        migrations.RemoveField(
            model_name="uniformeproductnaam",
            name="grondslag",
        ),
        migrations.RemoveField(
            model_name="uniformeproductnaam",
            name="grondslaglabel",
        ),
        migrations.RemoveField(
            model_name="uniformeproductnaam",
            name="grondslaglink",
        ),
        migrations.AlterField(
            model_name="uniformeproductnaam",
            name="upn_uri",
            field=models.URLField(
                help_text="Uniforme Productnaam URI van landelijk product",
                unique=True,
                verbose_name="UPN URI",
            ),
        ),
    ]
