# Generated by Django 2.2.24 on 2021-12-13 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20211130_1725"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniformeproductnaam",
            name="sdg",
        ),
    ]
