# Generated by Django 2.2.24 on 2021-12-13 11:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_uniformeproductnaam_sdg"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="sdg",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=4),
                blank=True,
                default=list,
                size=None,
                verbose_name="sdg",
            ),
        ),
    ]
