# Generated by Django 2.2.24 on 2022-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_uniformeproductnaam_sdg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informatiegebied",
            name="informatiegebied_uri",
            field=models.URLField(
                help_text="Informatiegebied URI van landelijk product",
                verbose_name="informatiegebied URI",
            ),
        ),
        migrations.AlterField(
            model_name="overheidsorganisatie",
            name="owms_end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="De einddatum, zoals gevonden in het OWMS-model.",
                null=True,
                verbose_name="einddatum",
            ),
        ),
        migrations.AlterField(
            model_name="overheidsorganisatie",
            name="owms_identifier",
            field=models.URLField(
                help_text="De metadatastandaard voor informatie van de nederlandse overheid op internet.",
                unique=True,
                verbose_name="OWMS identificatie",
            ),
        ),
        migrations.AlterField(
            model_name="overheidsorganisatie",
            name="owms_pref_label",
            field=models.CharField(
                help_text="De wettelijk erkende naam van de organisatie.",
                max_length=200,
                verbose_name="OWMS label",
            ),
        ),
    ]
