# Generated by Django 2.2.24 on 2022-01-13 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_uniformeproductnaam_sdg"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFieldConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_product_aanwezig",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Algemene aanwezigheid",
                    ),
                ),
                (
                    "product_product_aanwezig_toelichting",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Algemene aanwezigheid toelichting",
                    ),
                ),
                (
                    "product_locaties",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Algemene locaties",
                    ),
                ),
                (
                    "productversie_publicatie_datum",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Algemene publicatie datum",
                    ),
                ),
                (
                    "localizedgeneriekproduct_product_titel",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke product titel",
                    ),
                ),
                (
                    "localizedgeneriekproduct_generieke_tekst",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke tekst",
                    ),
                ),
                (
                    "localizedgeneriekproduct_korte_omschrijving",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke korte omschrijving",
                    ),
                ),
                (
                    "localizedgeneriekproduct_datum_check",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke datum check",
                    ),
                ),
                (
                    "localizedgeneriekproduct_verwijzing_links",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke verwijzing links",
                    ),
                ),
                (
                    "localizedgeneriekproduct_landelijke_link",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke landelijke link",
                    ),
                ),
                (
                    "localizedproduct_product_titel_decentraal",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke product titel decentraal",
                    ),
                ),
                (
                    "localizedproduct_tekst",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke tekst",
                    ),
                ),
                (
                    "localizedproduct_verwijzing_links",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke verwijzing links",
                    ),
                ),
                (
                    "localizedproduct_decentrale_link",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke decentrale link",
                    ),
                ),
                (
                    "localizedproduct_datum_wijziging",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke datum wijziging",
                    ),
                ),
                (
                    "localizedproduct_procedure_beschrijving",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke procedure beschrijving",
                    ),
                ),
                (
                    "localizedproduct_vereisten",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke vereisten",
                    ),
                ),
                (
                    "localizedproduct_bewijs",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke bewijs",
                    ),
                ),
                (
                    "localizedproduct_bezwaar_en_beroep",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke bezwaar en beroep",
                    ),
                ),
                (
                    "localizedproduct_kosten_en_betaalmethoden",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke kosten en betaalmethoden",
                    ),
                ),
                (
                    "localizedproduct_uiterste_termijn",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke uiterste termijn",
                    ),
                ),
                (
                    "localizedproduct_wtd_bij_geen_reactie",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke wtd bij geen reactie",
                    ),
                ),
                (
                    "localizedproduct_decentrale_procedure_link",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke decentrale procedure link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product field configuratie",
                "verbose_name_plural": "Product field configuratie",
            },
        ),
    ]
