# Generated by Django 2.2.24 on 2022-01-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_productfieldconfiguration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfieldconfiguration",
            old_name="product_locaties",
            new_name="product_lokaties",
        ),
    ]
