# Generated by Django 2.2.24 on 2022-01-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20220122_1516"),
        ("core", "0016_auto_20220121_1437"),
    ]

    operations = []
