# Generated by Django 2.2.24 on 2022-01-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_merge_20220124_1110"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfieldconfiguration",
            old_name="product_lokaties",
            new_name="product_locaties",
        ),
    ]
