# Generated by Django 2.2.24 on 2022-03-04 18:02

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20220124_1111"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfieldconfiguration",
            name="localizedproduct_product_valt_onder_toelichting",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Specifieke product valt onder toelichting",
            ),
        ),
        migrations.AddField(
            model_name="productfieldconfiguration",
            name="product_product_valt_onder",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Algemene valt onder",
            ),
        ),
    ]
