# Generated by Django 2.2.25 on 2022-03-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20220304_1802"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfieldconfiguration",
            old_name="localizedproduct_tekst",
            new_name="localizedproduct_specifieke_tekst",
        ),
    ]
