# Generated by Django 2.2.25 on 2022-03-23 11:59

from django.db import migrations


def add_bevoegde_organisaties(apps, schema_editor):
    BevoegdeOrganisatie = apps.get_model("organisaties", "BevoegdeOrganisatie")
    LokaleOverheid = apps.get_model("organisaties", "LokaleOverheid")

    # Add initial bevoegde organisatie to municipality
    bevoegde_organisaties = []
    for lokale_overheid in LokaleOverheid.objects.all().select_related("organisatie"):
        bevoegde_organisaties.append(
            BevoegdeOrganisatie(
                naam=lokale_overheid.organisatie.owms_pref_label,
                lokale_overheid=lokale_overheid,
                organisatie=lokale_overheid.organisatie,
            )
        )
    BevoegdeOrganisatie.objects.bulk_create(bevoegde_organisaties)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_productfieldconfiguration_product_bevoegde_organisatie"),
        ("organisaties", "0017_auto_20220324_1221"),
    ]

    operations = [
        migrations.RunPython(add_bevoegde_organisaties, migrations.RunPython.noop),
    ]
