# Generated by Django 2.2.25 on 2022-03-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_auto_20220318_1302"),
        ("core", "0021_data_migration_add_lokaleoverheid_bevoegde_organisaties"),
    ]

    operations = []
