# Generated by Django 2.2.25 on 2022-04-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_auto_20220407_1847"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informatiegebied",
            name="code",
        ),
        migrations.AlterField(
            model_name="informatiegebied",
            name="informatiegebied_uri",
            field=models.URLField(
                help_text="Informatiegebied SDG URI van landelijk product",
                unique=True,
                verbose_name="informatiegebied URI",
            ),
        ),
        migrations.AlterField(
            model_name="thema",
            name="code",
            field=models.CharField(
                help_text="De SDG code van het desbetreffende informatiegebied.",
                max_length=32,
                unique=True,
                verbose_name="code",
            ),
        ),
    ]
