# Generated by Django 2.2.25 on 2022-04-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_auto_20220407_1906"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfieldconfiguration",
            name="product_product_aanwezig_toelichting",
        ),
    ]
