# Generated by Django 2.2.25 on 2022-04-26 12:34

from django.db import migrations


def remove_catalogs_from_expired_orgs(apps, schema_editor):
    ProductenCatalogus = apps.get_model("core", "ProductenCatalogus")
    ProductenCatalogus.objects.exclude(
        lokale_overheid__organisatie__owms_end_date=None
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0027_productfieldconfiguration_localizedproduct_product_aanwezig_toelichting",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_catalogs_from_expired_orgs, migrations.RunPython.noop
        ),
    ]
