# Generated by Django 3.2.13 on 2022-05-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20220426_1234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informatiegebied",
            options={
                "ordering": ["informatiegebied"],
                "verbose_name": "informatiegebied",
                "verbose_name_plural": "informatiegebieden",
            },
        ),
    ]
