# Generated by Django 3.2.13 on 2022-05-03 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20220426_1234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informatiegebied",
            options={
                "ordering": ["informatiegebied"],
                "verbose_name": "informatiegebied",
                "verbose_name_plural": "informatiegebieden",
            },
        ),
        migrations.AlterModelOptions(
            name="overheidsorganisatie",
            options={
                "ordering": ["owms_end_date"],
                "verbose_name": "overheidsorganisatie",
                "verbose_name_plural": "overheidsorganisaties",
            },
        ),
        migrations.AlterModelOptions(
            name="productencatalogus",
            options={
                "ordering": ["naam"],
                "verbose_name": "producten catalogus",
                "verbose_name_plural": "producten catalogi",
            },
        ),
        migrations.AlterModelOptions(
            name="thema",
            options={
                "ordering": ["thema"],
                "verbose_name": "thema",
                "verbose_name_plural": "thema's",
            },
        ),
        migrations.AlterModelOptions(
            name="uniformeproductnaam",
            options={
                "ordering": ["upn_label"],
                "verbose_name": "uniforme productnaam",
                "verbose_name_plural": "uniforme productnamen",
            },
        ),
    ]
