# Generated by Django 2.2.25 on 2022-05-03 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20220426_1234"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="informatiegebied",
            options={
                "ordering": ["informatiegebied"],
                "verbose_name": "informatiegebied",
                "verbose_name_plural": "informatiegebieden",
            },
        ),
        migrations.AlterModelOptions(
            name="overheidsorganisatie",
            options={
                "ordering": ["owms_pref_label", "owms_end_date"],
                "verbose_name": "overheidsorganisatie",
                "verbose_name_plural": "overheidsorganisaties",
            },
        ),
        migrations.AlterModelOptions(
            name="productencatalogus",
            options={
                "ordering": ["naam", "lokale_overheid"],
                "verbose_name": "producten catalogus",
                "verbose_name_plural": "producten catalogi",
            },
        ),
        migrations.AlterModelOptions(
            name="thema",
            options={
                "ordering": ["informatiegebied"],
                "verbose_name": "thema",
                "verbose_name_plural": "thema's",
            },
        ),
        migrations.AlterModelOptions(
            name="uniformeproductnaam",
            options={
                "ordering": ["upn_label"],
                "verbose_name": "uniforme productnaam",
                "verbose_name_plural": "uniforme productnamen",
            },
        ),
    ]
