# Generated by Django 3.2.13 on 2022-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_auto_20220524_1742"),
    ]

    operations = [
        migrations.AddField(
            model_name="productencatalogus",
            name="is_default_catalogus",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of dit de stabdaard catalogus is van de lokale overheid.",
                verbose_name="is standaard catalogus",
            ),
        ),
    ]
