# Generated by Django 3.2.13 on 2022-08-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_data_migration_set_is_default_catalogus_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniformeproductnaam",
            name="is_verwijderd",
            field=models.BooleanField(
                default=False,
                help_text="Geeft aan of het product verwijderd is.",
                verbose_name="Is verwijderd",
            ),
        ),
    ]
