# Generated by Django 3.2.13 on 2022-07-28 12:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_data_migration_set_is_default_catalogus_true"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalizedProductFieldConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "taal",
                    models.CharField(
                        choices=[("nl", "Nederlands"), ("en", "Engels")],
                        help_text="De taal waarin de betreffende tekst is geschreven.ISO 639-1 (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)",
                        max_length=2,
                        verbose_name="taal",
                    ),
                ),
                (
                    "localizedproduct_product_aanwezig_toelichting",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Product aanwezig toelichting",
                    ),
                ),
                (
                    "localizedproduct_product_valt_onder_toelichting",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Product valt onder toelichting",
                    ),
                ),
                (
                    "localizedgeneriekproduct_product_titel",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Product titel",
                    ),
                ),
                (
                    "localizedgeneriekproduct_generieke_tekst",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Generieke tekst",
                    ),
                ),
                (
                    "localizedgeneriekproduct_korte_omschrijving",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Korte omschrijving",
                    ),
                ),
                (
                    "localizedgeneriekproduct_datum_check",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Datum check",
                    ),
                ),
                (
                    "localizedgeneriekproduct_verwijzing_links",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Verwijzing links",
                    ),
                ),
                (
                    "localizedgeneriekproduct_landelijke_link",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Landelijke link",
                    ),
                ),
                (
                    "localizedproduct_product_titel_decentraal",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Product titel decentraal",
                    ),
                ),
                (
                    "localizedproduct_specifieke_tekst",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Specifieke tekst",
                    ),
                ),
                (
                    "localizedproduct_verwijzing_links",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Verwijzing links",
                    ),
                ),
                (
                    "localizedproduct_decentrale_link",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Decentrale link",
                    ),
                ),
                (
                    "localizedproduct_datum_wijziging",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Datum wijziging",
                    ),
                ),
                (
                    "localizedproduct_procedure_beschrijving",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Procedure beschrijving",
                    ),
                ),
                (
                    "localizedproduct_vereisten",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Vereisten",
                    ),
                ),
                (
                    "localizedproduct_bewijs",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Bewijs",
                    ),
                ),
                (
                    "localizedproduct_bezwaar_en_beroep",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Bezwaar en beroep",
                    ),
                ),
                (
                    "localizedproduct_kosten_en_betaalmethoden",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Kosten en betaalmethoden",
                    ),
                ),
                (
                    "localizedproduct_uiterste_termijn",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Uiterste termijn",
                    ),
                ),
                (
                    "localizedproduct_wtd_bij_geen_reactie",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Wtd bij geen reactie",
                    ),
                ),
                (
                    "localizedproduct_decentrale_procedure_link",
                    sdg.core.db.fields.DynamicArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=512), size=None
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Decentrale procedure link",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        help_text="De configuratie singelton van deze vertaling.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.productfieldconfiguration",
                        verbose_name="configuratie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertaald configuratie",
                "verbose_name_plural": "Vertaalde configuraties",
                "ordering": ["-taal"],
            },
        ),
        migrations.AddConstraint(
            model_name="localizedproductfieldconfiguration",
            constraint=models.UniqueConstraint(
                fields=("config", "taal"), name="unique_language_per_condig"
            ),
        ),
    ]
