# Generated by Django 3.2.13 on 2022-07-28 12:11

from django.db import migrations

from sdg.core.constants.product import TaalChoices


def create_and_migrate_config(apps, schema_editor):
    ProductFieldConfiguration = apps.get_model("core", "ProductFieldConfiguration")
    LocalizedProductFieldConfiguration = apps.get_model(
        "core", "LocalizedProductFieldConfiguration"
    )

    try:
        config = ProductFieldConfiguration.objects.get(id=1)
    except ProductFieldConfiguration.DoesNotExist:
        config = ProductFieldConfiguration.objects.create()

    LocalizedProductFieldConfiguration.objects.bulk_create(
        [
            LocalizedProductFieldConfiguration(
                config=config,
                taal=TaalChoices.nl,
                localizedproduct_product_aanwezig_toelichting=config.localizedproduct_product_aanwezig_toelichting,
                localizedproduct_product_valt_onder_toelichting=config.localizedproduct_product_valt_onder_toelichting,
                localizedgeneriekproduct_product_titel=config.localizedgeneriekproduct_product_titel,
                localizedgeneriekproduct_generieke_tekst=config.localizedgeneriekproduct_generieke_tekst,
                localizedgeneriekproduct_korte_omschrijving=config.localizedgeneriekproduct_korte_omschrijving,
                localizedgeneriekproduct_datum_check=config.localizedgeneriekproduct_datum_check,
                localizedgeneriekproduct_verwijzing_links=config.localizedgeneriekproduct_verwijzing_links,
                localizedgeneriekproduct_landelijke_link=config.localizedgeneriekproduct_landelijke_link,
                localizedproduct_product_titel_decentraal=config.localizedproduct_product_titel_decentraal,
                localizedproduct_specifieke_tekst=config.localizedproduct_specifieke_tekst,
                localizedproduct_verwijzing_links=config.localizedproduct_verwijzing_links,
                localizedproduct_decentrale_link=config.localizedproduct_decentrale_link,
                localizedproduct_datum_wijziging=config.localizedproduct_datum_wijziging,
                localizedproduct_procedure_beschrijving=config.localizedproduct_procedure_beschrijving,
                localizedproduct_vereisten=config.localizedproduct_vereisten,
                localizedproduct_bewijs=config.localizedproduct_bewijs,
                localizedproduct_bezwaar_en_beroep=config.localizedproduct_bezwaar_en_beroep,
                localizedproduct_kosten_en_betaalmethoden=config.localizedproduct_kosten_en_betaalmethoden,
                localizedproduct_uiterste_termijn=config.localizedproduct_uiterste_termijn,
                localizedproduct_wtd_bij_geen_reactie=config.localizedproduct_wtd_bij_geen_reactie,
                localizedproduct_decentrale_procedure_link=config.localizedproduct_decentrale_procedure_link,
            ),
            LocalizedProductFieldConfiguration(
                config=config,
                taal=TaalChoices.en,
                localizedproduct_product_aanwezig_toelichting=config.localizedproduct_product_aanwezig_toelichting,
                localizedproduct_product_valt_onder_toelichting=config.localizedproduct_product_valt_onder_toelichting,
                localizedgeneriekproduct_product_titel=config.localizedgeneriekproduct_product_titel,
                localizedgeneriekproduct_generieke_tekst=config.localizedgeneriekproduct_generieke_tekst,
                localizedgeneriekproduct_korte_omschrijving=config.localizedgeneriekproduct_korte_omschrijving,
                localizedgeneriekproduct_datum_check=config.localizedgeneriekproduct_datum_check,
                localizedgeneriekproduct_verwijzing_links=config.localizedgeneriekproduct_verwijzing_links,
                localizedgeneriekproduct_landelijke_link=config.localizedgeneriekproduct_landelijke_link,
                localizedproduct_product_titel_decentraal=config.localizedproduct_product_titel_decentraal,
                localizedproduct_specifieke_tekst=config.localizedproduct_specifieke_tekst,
                localizedproduct_verwijzing_links=config.localizedproduct_verwijzing_links,
                localizedproduct_decentrale_link=config.localizedproduct_decentrale_link,
                localizedproduct_datum_wijziging=config.localizedproduct_datum_wijziging,
                localizedproduct_procedure_beschrijving=config.localizedproduct_procedure_beschrijving,
                localizedproduct_vereisten=config.localizedproduct_vereisten,
                localizedproduct_bewijs=config.localizedproduct_bewijs,
                localizedproduct_bezwaar_en_beroep=config.localizedproduct_bezwaar_en_beroep,
                localizedproduct_kosten_en_betaalmethoden=config.localizedproduct_kosten_en_betaalmethoden,
                localizedproduct_uiterste_termijn=config.localizedproduct_uiterste_termijn,
                localizedproduct_wtd_bij_geen_reactie=config.localizedproduct_wtd_bij_geen_reactie,
                localizedproduct_decentrale_procedure_link=config.localizedproduct_decentrale_procedure_link,
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20220728_1211"),
    ]

    operations = [
        migrations.RunPython(create_and_migrate_config, migrations.RunPython.noop),
    ]
