# Generated by Django 3.2.13 on 2022-08-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_uniformeproductnaam_is_verwijderd"),
        ("core", "0035_auto_20220729_1630"),
    ]

    operations = []
