# Generated by Django 3.2.13 on 2022-10-03 12:27

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_merge_20220831_1608"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfieldconfiguration",
            name="productversie_interne_opmerkingen",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Interne opmerkingen",
            ),
        ),
    ]
