# Generated by Django 3.2.13 on 2022-10-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_merge_20220831_1608"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documentatie_titel",
                    models.CharField(
                        blank=True,
                        help_text="De titel voor de documentatie link.",
                        max_length=128,
                        verbose_name="Documentatietitel",
                    ),
                ),
                (
                    "documentatie_link",
                    models.URLField(
                        blank=True,
                        help_text="Link naar de documentatie van de API.",
                        verbose_name="Documentatielink",
                    ),
                ),
                (
                    "goatcounter_code",
                    models.CharField(
                        blank=True,
                        help_text="De code geleverd door goatcounter, d.w.z. https://[my-code].goatcounter.com. Zorg ervoor dat GoatCounter is toegestaan in het Content-Security-Policy als u het gebruikt.",
                        max_length=255,
                        verbose_name="GoatCounter code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siteconfiguratie",
                "verbose_name_plural": "Siteconfiguratie",
            },
        ),
    ]
