# Generated by Django 3.2.13 on 2022-10-19 16:39

from django.db import migrations, models
import sdg.core.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_productfieldconfiguration_productversie_interne_opmerkingen"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documentatie_titel",
                    models.CharField(
                        blank=True,
                        help_text="De titel voor de documentatie link.",
                        max_length=128,
                        verbose_name="Documentatietitel",
                    ),
                ),
                (
                    "documentatie_link",
                    models.URLField(
                        blank=True,
                        help_text="Link naar de documentatie van de API.",
                        verbose_name="Documentatielink",
                    ),
                ),
                (
                    "goatcounter_domain",
                    models.CharField(
                        blank=True,
                        help_text="Het domein waar goatcounter wordt gehost, bijvoorbeeld: example.com. Zorg ervoor dat het is toegestaan in het Content Security Policy als u het gebruikt.",
                        max_length=255,
                        validators=[sdg.core.models.validators.DomainValidator()],
                        verbose_name="GoatCounter domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Siteconfiguratie",
                "verbose_name_plural": "Siteconfiguratie",
            },
        ),
    ]
