# Generated by Django 3.2.13 on 2022-10-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_productfieldconfiguration_product_heeft_kosten"),
        ("core", "0038_siteconfiguration"),
    ]

    operations = []
