# Generated by Django 3.2.13 on 2022-10-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_siteconfiguration"),
        ("core", "0038_timelinelog_object_name__data_migration"),
    ]

    operations = []
