# Generated by Django 3.2.13 on 2022-10-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_merge_20221024_1651"),
        ("core", "0039_merge_20221027_1505"),
    ]

    operations = []
