# Generated by Django 3.2.16 on 2022-11-28 13:59

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0041_localizedproductfieldconfiguration_localizedproduct_decentrale_procedure_label",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productfieldconfiguration",
            name="product_api_zichtbaarheid",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Zichtbaarheid",
            ),
        ),
    ]
