# Generated by Django 3.2.16 on 2022-12-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0041_localizedproductfieldconfiguration_localizedproduct_decentrale_procedure_label",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productencatalogus",
            options={
                "ordering": ("naam",),
                "verbose_name": "producten catalogus",
                "verbose_name_plural": "producten catalogi",
            },
        ),
    ]
