# Generated by Django 3.2.16 on 2022-12-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_productfieldconfiguration_product_api_verborgen"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productencatalogus",
            options={
                "ordering": ("naam",),
                "verbose_name": "producten catalogus",
                "verbose_name_plural": "producten catalogi",
            },
        ),
    ]
