# Generated by Django 3.2.16 on 2023-04-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_productencatalogus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="overheidsorganisatie",
            name="dop_slug",
            field=models.SlugField(
                blank=True,
                help_text="De gemeente slug voor de ondernemersplein website gebaseerd op het OWMS pref label.",
                max_length=220,
                verbose_name="Ondernemersplein slug field",
            ),
        ),
        migrations.AddField(
            model_name="overheidsorganisatie",
            name="dpc_slug",
            field=models.SlugField(
                blank=True,
                help_text="De gemeente slug voor de ??? website gebaseerd op het OWMS pref label.",
                max_length=220,
                verbose_name="??? slug field",
            ),
        ),
    ]
