# Generated by Django 3.2.16 on 2023-04-06 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_productencatalogus_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="mail_text_changes_last_sent",
            field=models.DateField(
                default=datetime.date(2023, 4, 6),
                help_text="De aantal dagen since de laatse product update notificatie email task is getriggerd.",
                verbose_name="Mail text changes last send",
            ),
        ),
    ]
