# Generated by Django 3.2.16 on 2023-04-07 16:26

from compat import slugify
from django.db import migrations
from django.db.models import Q


def generate_overheids_organisatie_slugs(apps, schema_editor):
    overheids_organisaties = apps.get_model("core", "Overheidsorganisatie")
    overheids_organisaties = overheids_organisaties.objects.filter(
        Q(dpc_slug__exact="") | Q(dop_slug__exact="")
    )

    for org in overheids_organisaties:
        slug_field = slugify(org.owms_pref_label)

        if not org.dpc_slug:
            org.dpc_slug = slug_field

        if not org.dop_slug:
            org.dop_slug = slug_field

        org.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_auto_20230407_1626"),
    ]

    operations = [
        migrations.RunPython(
            generate_overheids_organisatie_slugs, migrations.RunPython.noop
        )
    ]
