# Generated by Django 3.2.16 on 2023-05-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_siteconfiguration_mail_text_changes_last_sent"),
        ("core", "0046_alter_overheidsorganisatie_dpc_slug"),
    ]

    operations = []
