# Generated by Django 3.2.18 on 2023-05-04 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_merge_20230502_1302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="mail_text_changes_last_sent",
            field=models.DateField(
                default=datetime.date.today,
                help_text="De aantal dagen since de laatse product update notificatie email task is getriggerd.",
                verbose_name="Mail text changes last send",
            ),
        ),
    ]
