# Generated by Django 3.2.23 on 2025-05-26 17:10

import django.contrib.postgres.fields
from django.db import migrations, models
import sdg.core.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_alter_siteconfiguration_mail_text_changes_last_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="productfieldconfiguration",
            name="product_automatisch_doordrukken",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Automatisch doordrukken",
            ),
        ),
        migrations.AddField(
            model_name="productfieldconfiguration",
            name="product_automatisch_doordrukken_datum",
            field=sdg.core.db.fields.DynamicArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(max_length=512), size=None
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Automatisch doordrukken datum",
            ),
        ),
    ]
