# Generated by Django 5.2 on 2026-04-07 18:02

import privates.fields
import privates.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_auto_20250526_1710"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationRapport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    privates.fields.PrivateMediaFileField(
                        null=True,
                        storage=privates.storages.PrivateMediaFileSystemStorage(),
                        upload_to="application/rapports",
                    ),
                ),
                ("gemaakt_op", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "statistiek",
                "verbose_name_plural": "statistieken",
                "ordering": ("-gemaakt_op",),
            },
        ),
    ]
